//
// AiAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class AiAPI {

    /**

     - parameter aiSuggestionRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func aiSuggestApi(aiSuggestionRequest: AiSuggestionRequest, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: AiSuggestion?, _ error: Error?) -> Void)) -> RequestTask {
        return aiSuggestApiWithRequestBuilder(aiSuggestionRequest: aiSuggestionRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - POST /api/v1/support/ai/suggest
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter aiSuggestionRequest: (body)  
     - returns: RequestBuilder<AiSuggestion> 
     */
    open class func aiSuggestApiWithRequestBuilder(aiSuggestionRequest: AiSuggestionRequest) -> RequestBuilder<AiSuggestion> {
        let localVariablePath = "/api/v1/support/ai/suggest"
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: aiSuggestionRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AiSuggestion>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter aiConfigDto: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createWorkerApi(aiConfigDto: AiConfigDto, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: AiWorkerConfig?, _ error: Error?) -> Void)) -> RequestTask {
        return createWorkerApiWithRequestBuilder(aiConfigDto: aiConfigDto).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - POST /api/v1/support/ai/workers
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter aiConfigDto: (body)  
     - returns: RequestBuilder<AiWorkerConfig> 
     */
    open class func createWorkerApiWithRequestBuilder(aiConfigDto: AiConfigDto) -> RequestBuilder<AiWorkerConfig> {
        let localVariablePath = "/api/v1/support/ai/workers"
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: aiConfigDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AiWorkerConfig>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listWorkersApi(apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: [AiWorkerConfig]?, _ error: Error?) -> Void)) -> RequestTask {
        return listWorkersApiWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /api/v1/support/ai/workers
     - Bearer Token:
       - type: http
       - name: bearer_token
     - returns: RequestBuilder<[AiWorkerConfig]> 
     */
    open class func listWorkersApiWithRequestBuilder() -> RequestBuilder<[AiWorkerConfig]> {
        let localVariablePath = "/api/v1/support/ai/workers"
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[AiWorkerConfig]>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter workerId: (path)  
     - parameter aiSuggestionRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func runWorkerApi(workerId: UUID, aiSuggestionRequest: AiSuggestionRequest, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: AiSuggestion?, _ error: Error?) -> Void)) -> RequestTask {
        return runWorkerApiWithRequestBuilder(workerId: workerId, aiSuggestionRequest: aiSuggestionRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - POST /api/v1/support/ai/workers/{worker_id}/run
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter workerId: (path)  
     - parameter aiSuggestionRequest: (body)  
     - returns: RequestBuilder<AiSuggestion> 
     */
    open class func runWorkerApiWithRequestBuilder(workerId: UUID, aiSuggestionRequest: AiSuggestionRequest) -> RequestBuilder<AiSuggestion> {
        var localVariablePath = "/api/v1/support/ai/workers/{worker_id}/run"
        let workerIdPreEscape = "\(APIHelper.mapValueToPathItem(workerId))"
        let workerIdPostEscape = workerIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{worker_id}", with: workerIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: aiSuggestionRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AiSuggestion>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
