//
// ContactAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ContactAPI {

    /**
     Serve JSON Schema for client-side validation
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func contactSchema(apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return contactSchemaWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Serve JSON Schema for client-side validation
     - GET /api/v1/contacts/schema
     - Bearer Token:
       - type: http
       - name: bearer_token
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func contactSchemaWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/api/v1/contacts/schema"
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get the full per-contact timeline (Xentral §4.6/4.7).
     
     - parameter contactId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func contactTimeline(contactId: String, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: ContactTimelineResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return contactTimelineWithRequestBuilder(contactId: contactId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get the full per-contact timeline (Xentral §4.6/4.7).
     - GET /api/v1/contacts/{contact_id}/timeline
     - Aggregates communications, quotations, orders, invoices and uploaded documents for a contact, merged into a single reverse-chronological feed.
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter contactId: (path)  
     - returns: RequestBuilder<ContactTimelineResponse> 
     */
    open class func contactTimelineWithRequestBuilder(contactId: String) -> RequestBuilder<ContactTimelineResponse> {
        var localVariablePath = "/api/v1/contacts/{contact_id}/timeline"
        let contactIdPreEscape = "\(APIHelper.mapValueToPathItem(contactId))"
        let contactIdPostEscape = contactIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{contact_id}", with: contactIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ContactTimelineResponse>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create contact
     
     - parameter body: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createContact(body: AnyCodable, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: Contact?, _ error: Error?) -> Void)) -> RequestTask {
        return createContactWithRequestBuilder(body: body).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create contact
     - POST /api/v1/contacts
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter body: (body)  
     - returns: RequestBuilder<Contact> 
     */
    open class func createContactWithRequestBuilder(body: AnyCodable) -> RequestBuilder<Contact> {
        let localVariablePath = "/api/v1/contacts"
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Contact>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Soft-delete contact
     
     - parameter contactId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deleteContact(contactId: String, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteContactWithRequestBuilder(contactId: contactId).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Soft-delete contact
     - DELETE /api/v1/contacts/{contact_id}
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter contactId: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func deleteContactWithRequestBuilder(contactId: String) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/contacts/{contact_id}"
        let contactIdPreEscape = "\(APIHelper.mapValueToPathItem(contactId))"
        let contactIdPostEscape = contactIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{contact_id}", with: contactIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get single contact
     
     - parameter contactId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getContact(contactId: String, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: Contact?, _ error: Error?) -> Void)) -> RequestTask {
        return getContactWithRequestBuilder(contactId: contactId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get single contact
     - GET /api/v1/contacts/{contact_id}
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter contactId: (path)  
     - returns: RequestBuilder<Contact> 
     */
    open class func getContactWithRequestBuilder(contactId: String) -> RequestBuilder<Contact> {
        var localVariablePath = "/api/v1/contacts/{contact_id}"
        let contactIdPreEscape = "\(APIHelper.mapValueToPathItem(contactId))"
        let contactIdPostEscape = contactIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{contact_id}", with: contactIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Contact>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List contacts with search, type filter, and pagination
     
     - parameter page: (query)  (optional)
     - parameter pageSize: (query)  (optional)
     - parameter search: (query)  (optional)
     - parameter contactType: (query)  (optional)
     - parameter tag: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listContacts(page: Int? = nil, pageSize: Int? = nil, search: String? = nil, contactType: String? = nil, tag: String? = nil, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: [Contact]?, _ error: Error?) -> Void)) -> RequestTask {
        return listContactsWithRequestBuilder(page: page, pageSize: pageSize, search: search, contactType: contactType, tag: tag).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List contacts with search, type filter, and pagination
     - GET /api/v1/contacts
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter page: (query)  (optional)
     - parameter pageSize: (query)  (optional)
     - parameter search: (query)  (optional)
     - parameter contactType: (query)  (optional)
     - parameter tag: (query)  (optional)
     - returns: RequestBuilder<[Contact]> 
     */
    open class func listContactsWithRequestBuilder(page: Int? = nil, pageSize: Int? = nil, search: String? = nil, contactType: String? = nil, tag: String? = nil) -> RequestBuilder<[Contact]> {
        let localVariablePath = "/api/v1/contacts"
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "page_size": (wrappedValue: pageSize?.encodeToJSON(), isExplode: true),
            "search": (wrappedValue: search?.encodeToJSON(), isExplode: true),
            "contact_type": (wrappedValue: contactType?.encodeToJSON(), isExplode: true),
            "tag": (wrappedValue: tag?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Contact]>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Sales volume per contact
     
     - parameter page: (query)  (optional)
     - parameter pageSize: (query)  (optional)
     - parameter search: (query)  (optional)
     - parameter contactType: (query)  (optional)
     - parameter tag: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func salesVolume(page: Int? = nil, pageSize: Int? = nil, search: String? = nil, contactType: String? = nil, tag: String? = nil, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: SalesVolumeReport?, _ error: Error?) -> Void)) -> RequestTask {
        return salesVolumeWithRequestBuilder(page: page, pageSize: pageSize, search: search, contactType: contactType, tag: tag).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Sales volume per contact
     - GET /api/v1/contacts/sales-volume
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter page: (query)  (optional)
     - parameter pageSize: (query)  (optional)
     - parameter search: (query)  (optional)
     - parameter contactType: (query)  (optional)
     - parameter tag: (query)  (optional)
     - returns: RequestBuilder<SalesVolumeReport> 
     */
    open class func salesVolumeWithRequestBuilder(page: Int? = nil, pageSize: Int? = nil, search: String? = nil, contactType: String? = nil, tag: String? = nil) -> RequestBuilder<SalesVolumeReport> {
        let localVariablePath = "/api/v1/contacts/sales-volume"
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "page_size": (wrappedValue: pageSize?.encodeToJSON(), isExplode: true),
            "search": (wrappedValue: search?.encodeToJSON(), isExplode: true),
            "contact_type": (wrappedValue: contactType?.encodeToJSON(), isExplode: true),
            "tag": (wrappedValue: tag?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SalesVolumeReport>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update contact
     
     - parameter contactId: (path)  
     - parameter body: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updateContact(contactId: String, body: AnyCodable, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: Contact?, _ error: Error?) -> Void)) -> RequestTask {
        return updateContactWithRequestBuilder(contactId: contactId, body: body).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update contact
     - PUT /api/v1/contacts/{contact_id}
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter contactId: (path)  
     - parameter body: (body)  
     - returns: RequestBuilder<Contact> 
     */
    open class func updateContactWithRequestBuilder(contactId: String, body: AnyCodable) -> RequestBuilder<Contact> {
        var localVariablePath = "/api/v1/contacts/{contact_id}"
        let contactIdPreEscape = "\(APIHelper.mapValueToPathItem(contactId))"
        let contactIdPostEscape = contactIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{contact_id}", with: contactIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Contact>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
