//
// CreditNoteAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class CreditNoteAPI {

    /**

     - parameter body: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createCreditNote(body: AnyCodable, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: Invoice?, _ error: Error?) -> Void)) -> RequestTask {
        return createCreditNoteWithRequestBuilder(body: body).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - POST /api/v1/credit-notes
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter body: (body)  
     - returns: RequestBuilder<Invoice> 
     */
    open class func createCreditNoteWithRequestBuilder(body: AnyCodable) -> RequestBuilder<Invoice> {
        let localVariablePath = "/api/v1/credit-notes"
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Invoice>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter creditNoteId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func downloadCreditNotePdf(creditNoteId: String, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return downloadCreditNotePdfWithRequestBuilder(creditNoteId: creditNoteId).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /api/v1/credit-notes/{credit_note_id}/pdf
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter creditNoteId: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func downloadCreditNotePdfWithRequestBuilder(creditNoteId: String) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/credit-notes/{credit_note_id}/pdf"
        let creditNoteIdPreEscape = "\(APIHelper.mapValueToPathItem(creditNoteId))"
        let creditNoteIdPostEscape = creditNoteIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{credit_note_id}", with: creditNoteIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter creditNoteId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getCreditNote(creditNoteId: String, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: Invoice?, _ error: Error?) -> Void)) -> RequestTask {
        return getCreditNoteWithRequestBuilder(creditNoteId: creditNoteId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /api/v1/credit-notes/{credit_note_id}
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter creditNoteId: (path)  
     - returns: RequestBuilder<Invoice> 
     */
    open class func getCreditNoteWithRequestBuilder(creditNoteId: String) -> RequestBuilder<Invoice> {
        var localVariablePath = "/api/v1/credit-notes/{credit_note_id}"
        let creditNoteIdPreEscape = "\(APIHelper.mapValueToPathItem(creditNoteId))"
        let creditNoteIdPostEscape = creditNoteIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{credit_note_id}", with: creditNoteIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Invoice>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter page: (query)  (optional)
     - parameter pageSize: (query)  (optional)
     - parameter search: (query)  (optional)
     - parameter includeDeleted: (query) Soft-delete entities: set true to include rows with &#x60;deleted_at&#x60; set. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listCreditNotes(page: Int? = nil, pageSize: Int? = nil, search: String? = nil, includeDeleted: Bool? = nil, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: [Invoice]?, _ error: Error?) -> Void)) -> RequestTask {
        return listCreditNotesWithRequestBuilder(page: page, pageSize: pageSize, search: search, includeDeleted: includeDeleted).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /api/v1/credit-notes/
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter page: (query)  (optional)
     - parameter pageSize: (query)  (optional)
     - parameter search: (query)  (optional)
     - parameter includeDeleted: (query) Soft-delete entities: set true to include rows with &#x60;deleted_at&#x60; set. (optional)
     - returns: RequestBuilder<[Invoice]> 
     */
    open class func listCreditNotesWithRequestBuilder(page: Int? = nil, pageSize: Int? = nil, search: String? = nil, includeDeleted: Bool? = nil) -> RequestBuilder<[Invoice]> {
        let localVariablePath = "/api/v1/credit-notes/"
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "page_size": (wrappedValue: pageSize?.encodeToJSON(), isExplode: true),
            "search": (wrappedValue: search?.encodeToJSON(), isExplode: true),
            "include_deleted": (wrappedValue: includeDeleted?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Invoice]>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
