//
// CustomerGroupAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class CustomerGroupAPI {

    /**

     - parameter customerGroupId: (path)  
     - parameter body: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func addGroupMembers(customerGroupId: String, body: AnyCodable, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: CustomerGroup?, _ error: Error?) -> Void)) -> RequestTask {
        return addGroupMembersWithRequestBuilder(customerGroupId: customerGroupId, body: body).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - POST /api/v1/customer-groups/{customer_group_id}/members
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter customerGroupId: (path)  
     - parameter body: (body)  
     - returns: RequestBuilder<CustomerGroup> 
     */
    open class func addGroupMembersWithRequestBuilder(customerGroupId: String, body: AnyCodable) -> RequestBuilder<CustomerGroup> {
        var localVariablePath = "/api/v1/customer-groups/{customer_group_id}/members"
        let customerGroupIdPreEscape = "\(APIHelper.mapValueToPathItem(customerGroupId))"
        let customerGroupIdPostEscape = customerGroupIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{customer_group_id}", with: customerGroupIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CustomerGroup>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter customerGroupCreate: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createCustomerGroup(customerGroupCreate: CustomerGroupCreate, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: CustomerGroup?, _ error: Error?) -> Void)) -> RequestTask {
        return createCustomerGroupWithRequestBuilder(customerGroupCreate: customerGroupCreate).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - POST /api/v1/customer-groups
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter customerGroupCreate: (body)  
     - returns: RequestBuilder<CustomerGroup> 
     */
    open class func createCustomerGroupWithRequestBuilder(customerGroupCreate: CustomerGroupCreate) -> RequestBuilder<CustomerGroup> {
        let localVariablePath = "/api/v1/customer-groups"
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: customerGroupCreate)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CustomerGroup>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter customerGroupId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deleteCustomerGroup(customerGroupId: String, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteCustomerGroupWithRequestBuilder(customerGroupId: customerGroupId).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - DELETE /api/v1/customer-groups/{customer_group_id}
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter customerGroupId: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func deleteCustomerGroupWithRequestBuilder(customerGroupId: String) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/customer-groups/{customer_group_id}"
        let customerGroupIdPreEscape = "\(APIHelper.mapValueToPathItem(customerGroupId))"
        let customerGroupIdPostEscape = customerGroupIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{customer_group_id}", with: customerGroupIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter customerGroupId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getCustomerGroup(customerGroupId: String, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: CustomerGroup?, _ error: Error?) -> Void)) -> RequestTask {
        return getCustomerGroupWithRequestBuilder(customerGroupId: customerGroupId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /api/v1/customer-groups/{customer_group_id}
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter customerGroupId: (path)  
     - returns: RequestBuilder<CustomerGroup> 
     */
    open class func getCustomerGroupWithRequestBuilder(customerGroupId: String) -> RequestBuilder<CustomerGroup> {
        var localVariablePath = "/api/v1/customer-groups/{customer_group_id}"
        let customerGroupIdPreEscape = "\(APIHelper.mapValueToPathItem(customerGroupId))"
        let customerGroupIdPostEscape = customerGroupIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{customer_group_id}", with: customerGroupIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CustomerGroup>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter page: (query)  (optional)
     - parameter pageSize: (query)  (optional)
     - parameter search: (query)  (optional)
     - parameter includeDeleted: (query) Soft-delete entities: set true to include rows with &#x60;deleted_at&#x60; set. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listCustomerGroups(page: Int? = nil, pageSize: Int? = nil, search: String? = nil, includeDeleted: Bool? = nil, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: [CustomerGroup]?, _ error: Error?) -> Void)) -> RequestTask {
        return listCustomerGroupsWithRequestBuilder(page: page, pageSize: pageSize, search: search, includeDeleted: includeDeleted).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /api/v1/customer-groups/
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter page: (query)  (optional)
     - parameter pageSize: (query)  (optional)
     - parameter search: (query)  (optional)
     - parameter includeDeleted: (query) Soft-delete entities: set true to include rows with &#x60;deleted_at&#x60; set. (optional)
     - returns: RequestBuilder<[CustomerGroup]> 
     */
    open class func listCustomerGroupsWithRequestBuilder(page: Int? = nil, pageSize: Int? = nil, search: String? = nil, includeDeleted: Bool? = nil) -> RequestBuilder<[CustomerGroup]> {
        let localVariablePath = "/api/v1/customer-groups/"
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "page_size": (wrappedValue: pageSize?.encodeToJSON(), isExplode: true),
            "search": (wrappedValue: search?.encodeToJSON(), isExplode: true),
            "include_deleted": (wrappedValue: includeDeleted?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[CustomerGroup]>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter customerGroupId: (path)  
     - parameter customerGroupUpdate: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updateCustomerGroup(customerGroupId: String, customerGroupUpdate: CustomerGroupUpdate, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: CustomerGroup?, _ error: Error?) -> Void)) -> RequestTask {
        return updateCustomerGroupWithRequestBuilder(customerGroupId: customerGroupId, customerGroupUpdate: customerGroupUpdate).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - PUT /api/v1/customer-groups/{customer_group_id}
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter customerGroupId: (path)  
     - parameter customerGroupUpdate: (body)  
     - returns: RequestBuilder<CustomerGroup> 
     */
    open class func updateCustomerGroupWithRequestBuilder(customerGroupId: String, customerGroupUpdate: CustomerGroupUpdate) -> RequestBuilder<CustomerGroup> {
        var localVariablePath = "/api/v1/customer-groups/{customer_group_id}"
        let customerGroupIdPreEscape = "\(APIHelper.mapValueToPathItem(customerGroupId))"
        let customerGroupIdPostEscape = customerGroupIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{customer_group_id}", with: customerGroupIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: customerGroupUpdate)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CustomerGroup>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
