//
// EmailTemplateAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class EmailTemplateAPI {

    /**

     - parameter emailTemplateCreate: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createEmailTemplate(emailTemplateCreate: EmailTemplateCreate, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: EmailTemplate?, _ error: Error?) -> Void)) -> RequestTask {
        return createEmailTemplateWithRequestBuilder(emailTemplateCreate: emailTemplateCreate).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - POST /api/v1/email-templates
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter emailTemplateCreate: (body)  
     - returns: RequestBuilder<EmailTemplate> 
     */
    open class func createEmailTemplateWithRequestBuilder(emailTemplateCreate: EmailTemplateCreate) -> RequestBuilder<EmailTemplate> {
        let localVariablePath = "/api/v1/email-templates"
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: emailTemplateCreate)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EmailTemplate>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter emailTemplateId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deleteEmailTemplate(emailTemplateId: String, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteEmailTemplateWithRequestBuilder(emailTemplateId: emailTemplateId).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - DELETE /api/v1/email-templates/{email_template_id}
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter emailTemplateId: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func deleteEmailTemplateWithRequestBuilder(emailTemplateId: String) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/email-templates/{email_template_id}"
        let emailTemplateIdPreEscape = "\(APIHelper.mapValueToPathItem(emailTemplateId))"
        let emailTemplateIdPostEscape = emailTemplateIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{email_template_id}", with: emailTemplateIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter emailTemplateId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getEmailTemplate(emailTemplateId: String, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: EmailTemplate?, _ error: Error?) -> Void)) -> RequestTask {
        return getEmailTemplateWithRequestBuilder(emailTemplateId: emailTemplateId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /api/v1/email-templates/{email_template_id}
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter emailTemplateId: (path)  
     - returns: RequestBuilder<EmailTemplate> 
     */
    open class func getEmailTemplateWithRequestBuilder(emailTemplateId: String) -> RequestBuilder<EmailTemplate> {
        var localVariablePath = "/api/v1/email-templates/{email_template_id}"
        let emailTemplateIdPreEscape = "\(APIHelper.mapValueToPathItem(emailTemplateId))"
        let emailTemplateIdPostEscape = emailTemplateIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{email_template_id}", with: emailTemplateIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EmailTemplate>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter page: (query)  (optional)
     - parameter pageSize: (query)  (optional)
     - parameter status: (query)  (optional)
     - parameter search: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listEmailTemplates(page: Int? = nil, pageSize: Int? = nil, status: String? = nil, search: String? = nil, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: [EmailTemplate]?, _ error: Error?) -> Void)) -> RequestTask {
        return listEmailTemplatesWithRequestBuilder(page: page, pageSize: pageSize, status: status, search: search).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /api/v1/email-templates/
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter page: (query)  (optional)
     - parameter pageSize: (query)  (optional)
     - parameter status: (query)  (optional)
     - parameter search: (query)  (optional)
     - returns: RequestBuilder<[EmailTemplate]> 
     */
    open class func listEmailTemplatesWithRequestBuilder(page: Int? = nil, pageSize: Int? = nil, status: String? = nil, search: String? = nil) -> RequestBuilder<[EmailTemplate]> {
        let localVariablePath = "/api/v1/email-templates/"
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "pageSize": (wrappedValue: pageSize?.encodeToJSON(), isExplode: true),
            "status": (wrappedValue: status?.encodeToJSON(), isExplode: true),
            "search": (wrappedValue: search?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[EmailTemplate]>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter emailTemplateId: (path)  
     - parameter body: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func renderEmailTemplate(emailTemplateId: String, body: AnyCodable, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return renderEmailTemplateWithRequestBuilder(emailTemplateId: emailTemplateId, body: body).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - POST /api/v1/email-templates/{email_template_id}/render
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter emailTemplateId: (path)  
     - parameter body: (body)  
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func renderEmailTemplateWithRequestBuilder(emailTemplateId: String, body: AnyCodable) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/api/v1/email-templates/{email_template_id}/render"
        let emailTemplateIdPreEscape = "\(APIHelper.mapValueToPathItem(emailTemplateId))"
        let emailTemplateIdPostEscape = emailTemplateIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{email_template_id}", with: emailTemplateIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter emailTemplateId: (path)  
     - parameter emailTemplateUpdate: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updateEmailTemplate(emailTemplateId: String, emailTemplateUpdate: EmailTemplateUpdate, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: EmailTemplate?, _ error: Error?) -> Void)) -> RequestTask {
        return updateEmailTemplateWithRequestBuilder(emailTemplateId: emailTemplateId, emailTemplateUpdate: emailTemplateUpdate).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - PUT /api/v1/email-templates/{email_template_id}
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter emailTemplateId: (path)  
     - parameter emailTemplateUpdate: (body)  
     - returns: RequestBuilder<EmailTemplate> 
     */
    open class func updateEmailTemplateWithRequestBuilder(emailTemplateId: String, emailTemplateUpdate: EmailTemplateUpdate) -> RequestBuilder<EmailTemplate> {
        var localVariablePath = "/api/v1/email-templates/{email_template_id}"
        let emailTemplateIdPreEscape = "\(APIHelper.mapValueToPathItem(emailTemplateId))"
        let emailTemplateIdPostEscape = emailTemplateIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{email_template_id}", with: emailTemplateIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: emailTemplateUpdate)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EmailTemplate>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
