//
// FristenAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class FristenAPI {

    /**

     - parameter bundesland: (query)  (optional)
     - parameter voranmeldungsrhythmus: (query)  (optional)
     - parameter dauerfristverlaengerung: (query)  (optional)
     - parameter estAktiv: (query)  (optional)
     - parameter gewstAktiv: (query)  (optional)
     - parameter monate: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func fristenApi(bundesland: String? = nil, voranmeldungsrhythmus: String? = nil, dauerfristverlaengerung: Bool? = nil, estAktiv: Bool? = nil, gewstAktiv: Bool? = nil, monate: Int? = nil, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: FristenErgebnis?, _ error: Error?) -> Void)) -> RequestTask {
        return fristenApiWithRequestBuilder(bundesland: bundesland, voranmeldungsrhythmus: voranmeldungsrhythmus, dauerfristverlaengerung: dauerfristverlaengerung, estAktiv: estAktiv, gewstAktiv: gewstAktiv, monate: monate).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /api/v1/bookkeeping/fristen
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter bundesland: (query)  (optional)
     - parameter voranmeldungsrhythmus: (query)  (optional)
     - parameter dauerfristverlaengerung: (query)  (optional)
     - parameter estAktiv: (query)  (optional)
     - parameter gewstAktiv: (query)  (optional)
     - parameter monate: (query)  (optional)
     - returns: RequestBuilder<FristenErgebnis> 
     */
    open class func fristenApiWithRequestBuilder(bundesland: String? = nil, voranmeldungsrhythmus: String? = nil, dauerfristverlaengerung: Bool? = nil, estAktiv: Bool? = nil, gewstAktiv: Bool? = nil, monate: Int? = nil) -> RequestBuilder<FristenErgebnis> {
        let localVariablePath = "/api/v1/bookkeeping/fristen"
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "bundesland": (wrappedValue: bundesland?.encodeToJSON(), isExplode: true),
            "voranmeldungsrhythmus": (wrappedValue: voranmeldungsrhythmus?.encodeToJSON(), isExplode: true),
            "dauerfristverlaengerung": (wrappedValue: dauerfristverlaengerung?.encodeToJSON(), isExplode: true),
            "est_aktiv": (wrappedValue: estAktiv?.encodeToJSON(), isExplode: true),
            "gewst_aktiv": (wrappedValue: gewstAktiv?.encodeToJSON(), isExplode: true),
            "monate": (wrappedValue: monate?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<FristenErgebnis>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
