//
// GewerbesteuerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class GewerbesteuerAPI {

    /**

     - parameter year: (query)  
     - parameter hebesatz: (query)  (optional)
     - parameter gewerbeertrag: (query)  (optional)
     - parameter country: (query)  (optional)
     - parameter gemeindeschluessel: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func gewerbesteuerApi(year: Int, hebesatz: String? = nil, gewerbeertrag: String? = nil, country: String? = nil, gemeindeschluessel: String? = nil, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: GewerbesteuerErgebnis?, _ error: Error?) -> Void)) -> RequestTask {
        return gewerbesteuerApiWithRequestBuilder(year: year, hebesatz: hebesatz, gewerbeertrag: gewerbeertrag, country: country, gemeindeschluessel: gemeindeschluessel).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /api/v1/bookkeeping/gewerbesteuer
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter year: (query)  
     - parameter hebesatz: (query)  (optional)
     - parameter gewerbeertrag: (query)  (optional)
     - parameter country: (query)  (optional)
     - parameter gemeindeschluessel: (query)  (optional)
     - returns: RequestBuilder<GewerbesteuerErgebnis> 
     */
    open class func gewerbesteuerApiWithRequestBuilder(year: Int, hebesatz: String? = nil, gewerbeertrag: String? = nil, country: String? = nil, gemeindeschluessel: String? = nil) -> RequestBuilder<GewerbesteuerErgebnis> {
        let localVariablePath = "/api/v1/bookkeeping/gewerbesteuer"
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "year": (wrappedValue: year.encodeToJSON(), isExplode: true),
            "hebesatz": (wrappedValue: hebesatz?.encodeToJSON(), isExplode: true),
            "gewerbeertrag": (wrappedValue: gewerbeertrag?.encodeToJSON(), isExplode: true),
            "country": (wrappedValue: country?.encodeToJSON(), isExplode: true),
            "gemeindeschluessel": (wrappedValue: gemeindeschluessel?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GewerbesteuerErgebnis>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
