//
// InventoryCountAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class InventoryCountAPI {

    /**

     - parameter inventoryCount: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createInventoryCount(inventoryCount: InventoryCount, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: InventoryCount?, _ error: Error?) -> Void)) -> RequestTask {
        return createInventoryCountWithRequestBuilder(inventoryCount: inventoryCount).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - POST /api/v1/inventory-counts
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter inventoryCount: (body)  
     - returns: RequestBuilder<InventoryCount> 
     */
    open class func createInventoryCountWithRequestBuilder(inventoryCount: InventoryCount) -> RequestBuilder<InventoryCount> {
        let localVariablePath = "/api/v1/inventory-counts"
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: inventoryCount)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<InventoryCount>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter inventoryCountId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deleteInventoryCount(inventoryCountId: String, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteInventoryCountWithRequestBuilder(inventoryCountId: inventoryCountId).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - DELETE /api/v1/inventory-counts/{inventory_count_id}
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter inventoryCountId: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func deleteInventoryCountWithRequestBuilder(inventoryCountId: String) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/inventory-counts/{inventory_count_id}"
        let inventoryCountIdPreEscape = "\(APIHelper.mapValueToPathItem(inventoryCountId))"
        let inventoryCountIdPostEscape = inventoryCountIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{inventory_count_id}", with: inventoryCountIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter generateCountRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func generateInventoryCount(generateCountRequest: GenerateCountRequest, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: InventoryCount?, _ error: Error?) -> Void)) -> RequestTask {
        return generateInventoryCountWithRequestBuilder(generateCountRequest: generateCountRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - POST /api/v1/inventory-counts/generate
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter generateCountRequest: (body)  
     - returns: RequestBuilder<InventoryCount> 
     */
    open class func generateInventoryCountWithRequestBuilder(generateCountRequest: GenerateCountRequest) -> RequestBuilder<InventoryCount> {
        let localVariablePath = "/api/v1/inventory-counts/generate"
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: generateCountRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<InventoryCount>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter inventoryCountId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getInventoryCount(inventoryCountId: String, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: InventoryCount?, _ error: Error?) -> Void)) -> RequestTask {
        return getInventoryCountWithRequestBuilder(inventoryCountId: inventoryCountId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /api/v1/inventory-counts/{inventory_count_id}
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter inventoryCountId: (path)  
     - returns: RequestBuilder<InventoryCount> 
     */
    open class func getInventoryCountWithRequestBuilder(inventoryCountId: String) -> RequestBuilder<InventoryCount> {
        var localVariablePath = "/api/v1/inventory-counts/{inventory_count_id}"
        let inventoryCountIdPreEscape = "\(APIHelper.mapValueToPathItem(inventoryCountId))"
        let inventoryCountIdPostEscape = inventoryCountIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{inventory_count_id}", with: inventoryCountIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<InventoryCount>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter page: (query)  (optional)
     - parameter pageSize: (query)  (optional)
     - parameter status: (query)  (optional)
     - parameter warehouseId: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listInventoryCounts(page: Int? = nil, pageSize: Int? = nil, status: String? = nil, warehouseId: String? = nil, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: [InventoryCount]?, _ error: Error?) -> Void)) -> RequestTask {
        return listInventoryCountsWithRequestBuilder(page: page, pageSize: pageSize, status: status, warehouseId: warehouseId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /api/v1/inventory-counts/
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter page: (query)  (optional)
     - parameter pageSize: (query)  (optional)
     - parameter status: (query)  (optional)
     - parameter warehouseId: (query)  (optional)
     - returns: RequestBuilder<[InventoryCount]> 
     */
    open class func listInventoryCountsWithRequestBuilder(page: Int? = nil, pageSize: Int? = nil, status: String? = nil, warehouseId: String? = nil) -> RequestBuilder<[InventoryCount]> {
        let localVariablePath = "/api/v1/inventory-counts/"
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "page_size": (wrappedValue: pageSize?.encodeToJSON(), isExplode: true),
            "status": (wrappedValue: status?.encodeToJSON(), isExplode: true),
            "warehouse_id": (wrappedValue: warehouseId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[InventoryCount]>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter inventoryCountId: (path)  
     - parameter body: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updateInventoryCount(inventoryCountId: String, body: AnyCodable, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: InventoryCount?, _ error: Error?) -> Void)) -> RequestTask {
        return updateInventoryCountWithRequestBuilder(inventoryCountId: inventoryCountId, body: body).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - PUT /api/v1/inventory-counts/{inventory_count_id}
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter inventoryCountId: (path)  
     - parameter body: (body)  
     - returns: RequestBuilder<InventoryCount> 
     */
    open class func updateInventoryCountWithRequestBuilder(inventoryCountId: String, body: AnyCodable) -> RequestBuilder<InventoryCount> {
        var localVariablePath = "/api/v1/inventory-counts/{inventory_count_id}"
        let inventoryCountIdPreEscape = "\(APIHelper.mapValueToPathItem(inventoryCountId))"
        let inventoryCountIdPostEscape = inventoryCountIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{inventory_count_id}", with: inventoryCountIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<InventoryCount>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter inventoryCountId: (path)  
     - parameter inventoryCountStatusUpdate: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updateInventoryCountStatus(inventoryCountId: String, inventoryCountStatusUpdate: InventoryCountStatusUpdate, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: InventoryCount?, _ error: Error?) -> Void)) -> RequestTask {
        return updateInventoryCountStatusWithRequestBuilder(inventoryCountId: inventoryCountId, inventoryCountStatusUpdate: inventoryCountStatusUpdate).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - PUT /api/v1/inventory-counts/{inventory_count_id}/status
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter inventoryCountId: (path)  
     - parameter inventoryCountStatusUpdate: (body)  
     - returns: RequestBuilder<InventoryCount> 
     */
    open class func updateInventoryCountStatusWithRequestBuilder(inventoryCountId: String, inventoryCountStatusUpdate: InventoryCountStatusUpdate) -> RequestBuilder<InventoryCount> {
        var localVariablePath = "/api/v1/inventory-counts/{inventory_count_id}/status"
        let inventoryCountIdPreEscape = "\(APIHelper.mapValueToPathItem(inventoryCountId))"
        let inventoryCountIdPostEscape = inventoryCountIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{inventory_count_id}", with: inventoryCountIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: inventoryCountStatusUpdate)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<InventoryCount>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
