//
// KstAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class KstAPI {

    /**

     - parameter year: (query)  
     - parameter gewinn: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func kstApi(year: Int, gewinn: String? = nil, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: KstErgebnis?, _ error: Error?) -> Void)) -> RequestTask {
        return kstApiWithRequestBuilder(year: year, gewinn: gewinn).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /api/v1/bookkeeping/kst
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter year: (query)  
     - parameter gewinn: (query)  (optional)
     - returns: RequestBuilder<KstErgebnis> 
     */
    open class func kstApiWithRequestBuilder(year: Int, gewinn: String? = nil) -> RequestBuilder<KstErgebnis> {
        let localVariablePath = "/api/v1/bookkeeping/kst"
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "year": (wrappedValue: year.encodeToJSON(), isExplode: true),
            "gewinn": (wrappedValue: gewinn?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<KstErgebnis>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
