//
// PlausibilityAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class PlausibilityAPI {

    /**

     - parameter dateFrom: (query)  (optional)
     - parameter dateTo: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func plausibilityCheckApi(dateFrom: String? = nil, dateTo: String? = nil, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: PlausibilityReport?, _ error: Error?) -> Void)) -> RequestTask {
        return plausibilityCheckApiWithRequestBuilder(dateFrom: dateFrom, dateTo: dateTo).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /api/v1/bookkeeping/plausibility
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter dateFrom: (query)  (optional)
     - parameter dateTo: (query)  (optional)
     - returns: RequestBuilder<PlausibilityReport> 
     */
    open class func plausibilityCheckApiWithRequestBuilder(dateFrom: String? = nil, dateTo: String? = nil) -> RequestBuilder<PlausibilityReport> {
        let localVariablePath = "/api/v1/bookkeeping/plausibility"
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "date_from": (wrappedValue: dateFrom?.encodeToJSON(), isExplode: true),
            "date_to": (wrappedValue: dateTo?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PlausibilityReport>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
