//
// QuotationAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class QuotationAPI {

    /**

     - parameter quotationCreate: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createQuotation(quotationCreate: QuotationCreate, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: Quotation?, _ error: Error?) -> Void)) -> RequestTask {
        return createQuotationWithRequestBuilder(quotationCreate: quotationCreate).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - POST /api/v1/quotations
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter quotationCreate: (body)  
     - returns: RequestBuilder<Quotation> 
     */
    open class func createQuotationWithRequestBuilder(quotationCreate: QuotationCreate) -> RequestBuilder<Quotation> {
        let localVariablePath = "/api/v1/quotations"
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: quotationCreate)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Quotation>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter quotationId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deleteQuotation(quotationId: String, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteQuotationWithRequestBuilder(quotationId: quotationId).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - DELETE /api/v1/quotations/{quotation_id}
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter quotationId: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func deleteQuotationWithRequestBuilder(quotationId: String) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/quotations/{quotation_id}"
        let quotationIdPreEscape = "\(APIHelper.mapValueToPathItem(quotationId))"
        let quotationIdPostEscape = quotationIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{quotation_id}", with: quotationIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter quotationId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func downloadQuotationPdf(quotationId: String, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return downloadQuotationPdfWithRequestBuilder(quotationId: quotationId).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /api/v1/quotations/{quotation_id}/pdf
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter quotationId: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func downloadQuotationPdfWithRequestBuilder(quotationId: String) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/quotations/{quotation_id}/pdf"
        let quotationIdPreEscape = "\(APIHelper.mapValueToPathItem(quotationId))"
        let quotationIdPostEscape = quotationIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{quotation_id}", with: quotationIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter quotationId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getQuotation(quotationId: String, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: Quotation?, _ error: Error?) -> Void)) -> RequestTask {
        return getQuotationWithRequestBuilder(quotationId: quotationId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /api/v1/quotations/{quotation_id}
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter quotationId: (path)  
     - returns: RequestBuilder<Quotation> 
     */
    open class func getQuotationWithRequestBuilder(quotationId: String) -> RequestBuilder<Quotation> {
        var localVariablePath = "/api/v1/quotations/{quotation_id}"
        let quotationIdPreEscape = "\(APIHelper.mapValueToPathItem(quotationId))"
        let quotationIdPostEscape = quotationIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{quotation_id}", with: quotationIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Quotation>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter page: (query)  (optional)
     - parameter pageSize: (query)  (optional)
     - parameter search: (query)  (optional)
     - parameter includeDeleted: (query) Soft-delete entities: set true to include rows with &#x60;deleted_at&#x60; set. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listQuotations(page: Int? = nil, pageSize: Int? = nil, search: String? = nil, includeDeleted: Bool? = nil, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: [Quotation]?, _ error: Error?) -> Void)) -> RequestTask {
        return listQuotationsWithRequestBuilder(page: page, pageSize: pageSize, search: search, includeDeleted: includeDeleted).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /api/v1/quotations/
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter page: (query)  (optional)
     - parameter pageSize: (query)  (optional)
     - parameter search: (query)  (optional)
     - parameter includeDeleted: (query) Soft-delete entities: set true to include rows with &#x60;deleted_at&#x60; set. (optional)
     - returns: RequestBuilder<[Quotation]> 
     */
    open class func listQuotationsWithRequestBuilder(page: Int? = nil, pageSize: Int? = nil, search: String? = nil, includeDeleted: Bool? = nil) -> RequestBuilder<[Quotation]> {
        let localVariablePath = "/api/v1/quotations/"
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "page_size": (wrappedValue: pageSize?.encodeToJSON(), isExplode: true),
            "search": (wrappedValue: search?.encodeToJSON(), isExplode: true),
            "include_deleted": (wrappedValue: includeDeleted?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Quotation]>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter quotationId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func pursueQuotation(quotationId: String, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: OrderConfirmation?, _ error: Error?) -> Void)) -> RequestTask {
        return pursueQuotationWithRequestBuilder(quotationId: quotationId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - POST /api/v1/quotations/{quotation_id}/pursue
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter quotationId: (path)  
     - returns: RequestBuilder<OrderConfirmation> 
     */
    open class func pursueQuotationWithRequestBuilder(quotationId: String) -> RequestBuilder<OrderConfirmation> {
        var localVariablePath = "/api/v1/quotations/{quotation_id}/pursue"
        let quotationIdPreEscape = "\(APIHelper.mapValueToPathItem(quotationId))"
        let quotationIdPostEscape = quotationIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{quotation_id}", with: quotationIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<OrderConfirmation>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter quotationId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func quotationRestore(quotationId: String, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: Quotation?, _ error: Error?) -> Void)) -> RequestTask {
        return quotationRestoreWithRequestBuilder(quotationId: quotationId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - POST /api/v1/quotations/{quotation_id}/restore
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter quotationId: (path)  
     - returns: RequestBuilder<Quotation> 
     */
    open class func quotationRestoreWithRequestBuilder(quotationId: String) -> RequestBuilder<Quotation> {
        var localVariablePath = "/api/v1/quotations/{quotation_id}/restore"
        let quotationIdPreEscape = "\(APIHelper.mapValueToPathItem(quotationId))"
        let quotationIdPostEscape = quotationIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{quotation_id}", with: quotationIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Quotation>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter quotationId: (path)  
     - parameter body: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updateQuotation(quotationId: String, body: AnyCodable, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: Quotation?, _ error: Error?) -> Void)) -> RequestTask {
        return updateQuotationWithRequestBuilder(quotationId: quotationId, body: body).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - PUT /api/v1/quotations/{quotation_id}
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter quotationId: (path)  
     - parameter body: (body)  
     - returns: RequestBuilder<Quotation> 
     */
    open class func updateQuotationWithRequestBuilder(quotationId: String, body: AnyCodable) -> RequestBuilder<Quotation> {
        var localVariablePath = "/api/v1/quotations/{quotation_id}"
        let quotationIdPreEscape = "\(APIHelper.mapValueToPathItem(quotationId))"
        let quotationIdPostEscape = quotationIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{quotation_id}", with: quotationIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Quotation>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
