//
// StockTransferAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class StockTransferAPI {

    /**

     - parameter stockTransfer: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createStockTransfer(stockTransfer: StockTransfer, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: StockTransfer?, _ error: Error?) -> Void)) -> RequestTask {
        return createStockTransferWithRequestBuilder(stockTransfer: stockTransfer).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - POST /api/v1/stock-transfers
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter stockTransfer: (body)  
     - returns: RequestBuilder<StockTransfer> 
     */
    open class func createStockTransferWithRequestBuilder(stockTransfer: StockTransfer) -> RequestBuilder<StockTransfer> {
        let localVariablePath = "/api/v1/stock-transfers"
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: stockTransfer)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StockTransfer>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter stockTransferId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deleteStockTransfer(stockTransferId: String, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteStockTransferWithRequestBuilder(stockTransferId: stockTransferId).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - DELETE /api/v1/stock-transfers/{stock_transfer_id}
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter stockTransferId: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func deleteStockTransferWithRequestBuilder(stockTransferId: String) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/stock-transfers/{stock_transfer_id}"
        let stockTransferIdPreEscape = "\(APIHelper.mapValueToPathItem(stockTransferId))"
        let stockTransferIdPostEscape = stockTransferIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{stock_transfer_id}", with: stockTransferIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter stockTransferId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getStockTransfer(stockTransferId: String, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: StockTransfer?, _ error: Error?) -> Void)) -> RequestTask {
        return getStockTransferWithRequestBuilder(stockTransferId: stockTransferId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /api/v1/stock-transfers/{stock_transfer_id}
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter stockTransferId: (path)  
     - returns: RequestBuilder<StockTransfer> 
     */
    open class func getStockTransferWithRequestBuilder(stockTransferId: String) -> RequestBuilder<StockTransfer> {
        var localVariablePath = "/api/v1/stock-transfers/{stock_transfer_id}"
        let stockTransferIdPreEscape = "\(APIHelper.mapValueToPathItem(stockTransferId))"
        let stockTransferIdPostEscape = stockTransferIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{stock_transfer_id}", with: stockTransferIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StockTransfer>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter page: (query)  (optional)
     - parameter pageSize: (query)  (optional)
     - parameter status: (query)  (optional)
     - parameter warehouseId: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listStockTransfers(page: Int? = nil, pageSize: Int? = nil, status: String? = nil, warehouseId: String? = nil, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: [StockTransfer]?, _ error: Error?) -> Void)) -> RequestTask {
        return listStockTransfersWithRequestBuilder(page: page, pageSize: pageSize, status: status, warehouseId: warehouseId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /api/v1/stock-transfers/
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter page: (query)  (optional)
     - parameter pageSize: (query)  (optional)
     - parameter status: (query)  (optional)
     - parameter warehouseId: (query)  (optional)
     - returns: RequestBuilder<[StockTransfer]> 
     */
    open class func listStockTransfersWithRequestBuilder(page: Int? = nil, pageSize: Int? = nil, status: String? = nil, warehouseId: String? = nil) -> RequestBuilder<[StockTransfer]> {
        let localVariablePath = "/api/v1/stock-transfers/"
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "page_size": (wrappedValue: pageSize?.encodeToJSON(), isExplode: true),
            "status": (wrappedValue: status?.encodeToJSON(), isExplode: true),
            "warehouse_id": (wrappedValue: warehouseId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[StockTransfer]>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter stockTransferId: (path)  
     - parameter stockTransferStatusUpdate: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updateStockTransferStatus(stockTransferId: String, stockTransferStatusUpdate: StockTransferStatusUpdate, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: StockTransfer?, _ error: Error?) -> Void)) -> RequestTask {
        return updateStockTransferStatusWithRequestBuilder(stockTransferId: stockTransferId, stockTransferStatusUpdate: stockTransferStatusUpdate).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - PUT /api/v1/stock-transfers/{stock_transfer_id}/status
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter stockTransferId: (path)  
     - parameter stockTransferStatusUpdate: (body)  
     - returns: RequestBuilder<StockTransfer> 
     */
    open class func updateStockTransferStatusWithRequestBuilder(stockTransferId: String, stockTransferStatusUpdate: StockTransferStatusUpdate) -> RequestBuilder<StockTransfer> {
        var localVariablePath = "/api/v1/stock-transfers/{stock_transfer_id}/status"
        let stockTransferIdPreEscape = "\(APIHelper.mapValueToPathItem(stockTransferId))"
        let stockTransferIdPostEscape = stockTransferIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{stock_transfer_id}", with: stockTransferIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: stockTransferStatusUpdate)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StockTransfer>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
