//
// SupplierInvoiceAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class SupplierInvoiceAPI {

    /**

     - parameter supplierInvoice: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createSupplierInvoice(supplierInvoice: SupplierInvoice, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: SupplierInvoice?, _ error: Error?) -> Void)) -> RequestTask {
        return createSupplierInvoiceWithRequestBuilder(supplierInvoice: supplierInvoice).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - POST /api/v1/supplier-invoices
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter supplierInvoice: (body)  
     - returns: RequestBuilder<SupplierInvoice> 
     */
    open class func createSupplierInvoiceWithRequestBuilder(supplierInvoice: SupplierInvoice) -> RequestBuilder<SupplierInvoice> {
        let localVariablePath = "/api/v1/supplier-invoices"
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: supplierInvoice)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SupplierInvoice>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter supplierInvoiceId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deleteSupplierInvoice(supplierInvoiceId: String, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteSupplierInvoiceWithRequestBuilder(supplierInvoiceId: supplierInvoiceId).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - DELETE /api/v1/supplier-invoices/{supplier_invoice_id}
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter supplierInvoiceId: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func deleteSupplierInvoiceWithRequestBuilder(supplierInvoiceId: String) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/supplier-invoices/{supplier_invoice_id}"
        let supplierInvoiceIdPreEscape = "\(APIHelper.mapValueToPathItem(supplierInvoiceId))"
        let supplierInvoiceIdPostEscape = supplierInvoiceIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{supplier_invoice_id}", with: supplierInvoiceIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter supplierInvoiceId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getSupplierInvoice(supplierInvoiceId: String, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: SupplierInvoice?, _ error: Error?) -> Void)) -> RequestTask {
        return getSupplierInvoiceWithRequestBuilder(supplierInvoiceId: supplierInvoiceId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /api/v1/supplier-invoices/{supplier_invoice_id}
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter supplierInvoiceId: (path)  
     - returns: RequestBuilder<SupplierInvoice> 
     */
    open class func getSupplierInvoiceWithRequestBuilder(supplierInvoiceId: String) -> RequestBuilder<SupplierInvoice> {
        var localVariablePath = "/api/v1/supplier-invoices/{supplier_invoice_id}"
        let supplierInvoiceIdPreEscape = "\(APIHelper.mapValueToPathItem(supplierInvoiceId))"
        let supplierInvoiceIdPostEscape = supplierInvoiceIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{supplier_invoice_id}", with: supplierInvoiceIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SupplierInvoice>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter page: (query)  (optional)
     - parameter pageSize: (query)  (optional)
     - parameter status: (query)  (optional)
     - parameter purchaseOrderId: (query)  (optional)
     - parameter supplierName: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func listSupplierInvoices(page: Int? = nil, pageSize: Int? = nil, status: String? = nil, purchaseOrderId: String? = nil, supplierName: String? = nil, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: [SupplierInvoice]?, _ error: Error?) -> Void)) -> RequestTask {
        return listSupplierInvoicesWithRequestBuilder(page: page, pageSize: pageSize, status: status, purchaseOrderId: purchaseOrderId, supplierName: supplierName).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /api/v1/supplier-invoices/
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter page: (query)  (optional)
     - parameter pageSize: (query)  (optional)
     - parameter status: (query)  (optional)
     - parameter purchaseOrderId: (query)  (optional)
     - parameter supplierName: (query)  (optional)
     - returns: RequestBuilder<[SupplierInvoice]> 
     */
    open class func listSupplierInvoicesWithRequestBuilder(page: Int? = nil, pageSize: Int? = nil, status: String? = nil, purchaseOrderId: String? = nil, supplierName: String? = nil) -> RequestBuilder<[SupplierInvoice]> {
        let localVariablePath = "/api/v1/supplier-invoices/"
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.encodeToJSON(), isExplode: true),
            "page_size": (wrappedValue: pageSize?.encodeToJSON(), isExplode: true),
            "status": (wrappedValue: status?.encodeToJSON(), isExplode: true),
            "purchase_order_id": (wrappedValue: purchaseOrderId?.encodeToJSON(), isExplode: true),
            "supplier_name": (wrappedValue: supplierName?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[SupplierInvoice]>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter supplierInvoiceId: (path)  
     - parameter body: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updateSupplierInvoice(supplierInvoiceId: String, body: AnyCodable, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: SupplierInvoice?, _ error: Error?) -> Void)) -> RequestTask {
        return updateSupplierInvoiceWithRequestBuilder(supplierInvoiceId: supplierInvoiceId, body: body).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - PUT /api/v1/supplier-invoices/{supplier_invoice_id}
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter supplierInvoiceId: (path)  
     - parameter body: (body)  
     - returns: RequestBuilder<SupplierInvoice> 
     */
    open class func updateSupplierInvoiceWithRequestBuilder(supplierInvoiceId: String, body: AnyCodable) -> RequestBuilder<SupplierInvoice> {
        var localVariablePath = "/api/v1/supplier-invoices/{supplier_invoice_id}"
        let supplierInvoiceIdPreEscape = "\(APIHelper.mapValueToPathItem(supplierInvoiceId))"
        let supplierInvoiceIdPostEscape = supplierInvoiceIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{supplier_invoice_id}", with: supplierInvoiceIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SupplierInvoice>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter supplierInvoiceId: (path)  
     - parameter supplierInvoiceStatusUpdate: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updateSupplierInvoiceStatus(supplierInvoiceId: String, supplierInvoiceStatusUpdate: SupplierInvoiceStatusUpdate, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: SupplierInvoice?, _ error: Error?) -> Void)) -> RequestTask {
        return updateSupplierInvoiceStatusWithRequestBuilder(supplierInvoiceId: supplierInvoiceId, supplierInvoiceStatusUpdate: supplierInvoiceStatusUpdate).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - PUT /api/v1/supplier-invoices/{supplier_invoice_id}/status
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter supplierInvoiceId: (path)  
     - parameter supplierInvoiceStatusUpdate: (body)  
     - returns: RequestBuilder<SupplierInvoice> 
     */
    open class func updateSupplierInvoiceStatusWithRequestBuilder(supplierInvoiceId: String, supplierInvoiceStatusUpdate: SupplierInvoiceStatusUpdate) -> RequestBuilder<SupplierInvoice> {
        var localVariablePath = "/api/v1/supplier-invoices/{supplier_invoice_id}/status"
        let supplierInvoiceIdPreEscape = "\(APIHelper.mapValueToPathItem(supplierInvoiceId))"
        let supplierInvoiceIdPostEscape = supplierInvoiceIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{supplier_invoice_id}", with: supplierInvoiceIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: supplierInvoiceStatusUpdate)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SupplierInvoice>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
