//
// ZugferdAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ZugferdAPI {

    /**

     - parameter id: (path)  
     - parameter supplierName: (query)  (optional)
     - parameter supplierStreet: (query)  (optional)
     - parameter supplierCity: (query)  (optional)
     - parameter supplierZip: (query)  (optional)
     - parameter supplierCountry: (query)  (optional)
     - parameter supplierVatId: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func generateZugferdApi(id: String, supplierName: String? = nil, supplierStreet: String? = nil, supplierCity: String? = nil, supplierZip: String? = nil, supplierCountry: String? = nil, supplierVatId: String? = nil, apiResponseQueue: DispatchQueue = SimpleBillyAPIAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return generateZugferdApiWithRequestBuilder(id: id, supplierName: supplierName, supplierStreet: supplierStreet, supplierCity: supplierCity, supplierZip: supplierZip, supplierCountry: supplierCountry, supplierVatId: supplierVatId).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /api/v1/invoices/{id}/zugferd
     - Bearer Token:
       - type: http
       - name: bearer_token
     - parameter id: (path)  
     - parameter supplierName: (query)  (optional)
     - parameter supplierStreet: (query)  (optional)
     - parameter supplierCity: (query)  (optional)
     - parameter supplierZip: (query)  (optional)
     - parameter supplierCountry: (query)  (optional)
     - parameter supplierVatId: (query)  (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func generateZugferdApiWithRequestBuilder(id: String, supplierName: String? = nil, supplierStreet: String? = nil, supplierCity: String? = nil, supplierZip: String? = nil, supplierCountry: String? = nil, supplierVatId: String? = nil) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/invoices/{id}/zugferd"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = SimpleBillyAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "supplier_name": (wrappedValue: supplierName?.encodeToJSON(), isExplode: true),
            "supplier_street": (wrappedValue: supplierStreet?.encodeToJSON(), isExplode: true),
            "supplier_city": (wrappedValue: supplierCity?.encodeToJSON(), isExplode: true),
            "supplier_zip": (wrappedValue: supplierZip?.encodeToJSON(), isExplode: true),
            "supplier_country": (wrappedValue: supplierCountry?.encodeToJSON(), isExplode: true),
            "supplier_vat_id": (wrappedValue: supplierVatId?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = SimpleBillyAPIAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
