//
// Absence.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Absence: Codable, JSONEncodable, Hashable {

    public static let notesRule = StringRule(minLength: nil, maxLength: 2000, pattern: nil)
    /** One of \"vacation\", \"sick\", \"sabbatical\", \"parental\", \"other\". */
    public var absenceType: AbsenceType?
    public var approvedAt: Date?
    /** References the user entity. */
    public var approvedBy: UUID?
    public var createdAt: Date?
    public var deletedAt: Date?
    /** References the employee entity. */
    public var employeeId: UUID?
    public var endDate: Date?
    public var id: UUID?
    public var notes: String?
    public var startDate: Date?
    /** One of \"pending\", \"approved\", \"rejected\", \"cancelled\". */
    public var status: AbsenceStatus?
    public var tenantId: UUID?
    public var updatedAt: Date?

    public init(absenceType: AbsenceType? = nil, approvedAt: Date? = nil, approvedBy: UUID? = nil, createdAt: Date? = nil, deletedAt: Date? = nil, employeeId: UUID? = nil, endDate: Date? = nil, id: UUID? = nil, notes: String? = nil, startDate: Date? = nil, status: AbsenceStatus? = nil, tenantId: UUID? = nil, updatedAt: Date? = nil) {
        self.absenceType = absenceType
        self.approvedAt = approvedAt
        self.approvedBy = approvedBy
        self.createdAt = createdAt
        self.deletedAt = deletedAt
        self.employeeId = employeeId
        self.endDate = endDate
        self.id = id
        self.notes = notes
        self.startDate = startDate
        self.status = status
        self.tenantId = tenantId
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case absenceType
        case approvedAt
        case approvedBy
        case createdAt
        case deletedAt
        case employeeId
        case endDate
        case id
        case notes
        case startDate
        case status
        case tenantId
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(absenceType, forKey: .absenceType)
        try container.encodeIfPresent(approvedAt, forKey: .approvedAt)
        try container.encodeIfPresent(approvedBy, forKey: .approvedBy)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(deletedAt, forKey: .deletedAt)
        try container.encodeIfPresent(employeeId, forKey: .employeeId)
        try container.encodeIfPresent(endDate, forKey: .endDate)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(startDate, forKey: .startDate)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(tenantId, forKey: .tenantId)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Absence: Identifiable {}
