//
// ActivityStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Activity status. */
public enum ActivityStatus: String, Codable, CaseIterable {
    case _open = "open"
    case done = "done"
    case cancelled = "cancelled"
}
