//
// AiWorkerConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AiWorkerConfig: Codable, JSONEncodable, Hashable {

    public var autoReply: Bool
    public var createdAt: Date
    public var id: UUID
    public var isActive: Bool
    public var maxToolCalls: Int
    public var model: String
    public var name: String
    public var provider: String
    public var systemPrompt: String
    public var tenantId: UUID
    public var triggerOn: [String]
    public var updatedAt: Date?

    public init(autoReply: Bool, createdAt: Date, id: UUID, isActive: Bool, maxToolCalls: Int, model: String, name: String, provider: String, systemPrompt: String, tenantId: UUID, triggerOn: [String], updatedAt: Date? = nil) {
        self.autoReply = autoReply
        self.createdAt = createdAt
        self.id = id
        self.isActive = isActive
        self.maxToolCalls = maxToolCalls
        self.model = model
        self.name = name
        self.provider = provider
        self.systemPrompt = systemPrompt
        self.tenantId = tenantId
        self.triggerOn = triggerOn
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case autoReply = "auto_reply"
        case createdAt = "created_at"
        case id
        case isActive = "is_active"
        case maxToolCalls = "max_tool_calls"
        case model
        case name
        case provider
        case systemPrompt = "system_prompt"
        case tenantId = "tenant_id"
        case triggerOn = "trigger_on"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(autoReply, forKey: .autoReply)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(id, forKey: .id)
        try container.encode(isActive, forKey: .isActive)
        try container.encode(maxToolCalls, forKey: .maxToolCalls)
        try container.encode(model, forKey: .model)
        try container.encode(name, forKey: .name)
        try container.encode(provider, forKey: .provider)
        try container.encode(systemPrompt, forKey: .systemPrompt)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(triggerOn, forKey: .triggerOn)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension AiWorkerConfig: Identifiable {}
