//
// AssignmentStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum AssignmentStatus: String, Codable, CaseIterable {
    case _required = "required"
    case completed = "completed"
    case overdue = "overdue"
    case waived = "waived"
}
