//
// Automation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Automation: Codable, JSONEncodable, Hashable {

    public var automationKey: String
    public var config: AnyCodable?
    public var createdAt: Date
    public var enabled: Bool
    public var lastRunAt: Date?
    public var nextRunAt: Date?
    public var tenantId: UUID
    public var updatedAt: Date

    public init(automationKey: String, config: AnyCodable?, createdAt: Date, enabled: Bool, lastRunAt: Date? = nil, nextRunAt: Date? = nil, tenantId: UUID, updatedAt: Date) {
        self.automationKey = automationKey
        self.config = config
        self.createdAt = createdAt
        self.enabled = enabled
        self.lastRunAt = lastRunAt
        self.nextRunAt = nextRunAt
        self.tenantId = tenantId
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case automationKey
        case config
        case createdAt
        case enabled
        case lastRunAt
        case nextRunAt
        case tenantId
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(automationKey, forKey: .automationKey)
        try container.encode(config, forKey: .config)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(enabled, forKey: .enabled)
        try container.encodeIfPresent(lastRunAt, forKey: .lastRunAt)
        try container.encodeIfPresent(nextRunAt, forKey: .nextRunAt)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}

