//
// Budget.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Budget: Codable, JSONEncodable, Hashable {

    /** Posting category key (matches `category` on journal entries). */
    public var category: String
    /** Monthly goal amount (gross). 0 means \"no goal set\". */
    public var monthlyGoal: String
    public var updatedAt: Date?
    /** Budget year the goal applies to. */
    public var year: Int

    public init(category: String, monthlyGoal: String, updatedAt: Date? = nil, year: Int) {
        self.category = category
        self.monthlyGoal = monthlyGoal
        self.updatedAt = updatedAt
        self.year = year
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case category
        case monthlyGoal
        case updatedAt
        case year
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(category, forKey: .category)
        try container.encode(monthlyGoal, forKey: .monthlyGoal)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encode(year, forKey: .year)
    }
}

