//
// CashflowReport.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CashflowReport: Codable, JSONEncodable, Hashable {

    public var closingBalance: Double
    public var financingCashflow: Double
    public var investingCashflow: Double
    public var netCashflow: Double
    public var openingBalance: Double
    public var operatingCashflow: Double
    public var period: String

    public init(closingBalance: Double, financingCashflow: Double, investingCashflow: Double, netCashflow: Double, openingBalance: Double, operatingCashflow: Double, period: String) {
        self.closingBalance = closingBalance
        self.financingCashflow = financingCashflow
        self.investingCashflow = investingCashflow
        self.netCashflow = netCashflow
        self.openingBalance = openingBalance
        self.operatingCashflow = operatingCashflow
        self.period = period
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case closingBalance = "closing_balance"
        case financingCashflow = "financing_cashflow"
        case investingCashflow = "investing_cashflow"
        case netCashflow = "net_cashflow"
        case openingBalance = "opening_balance"
        case operatingCashflow = "operating_cashflow"
        case period
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(closingBalance, forKey: .closingBalance)
        try container.encode(financingCashflow, forKey: .financingCashflow)
        try container.encode(investingCashflow, forKey: .investingCashflow)
        try container.encode(netCashflow, forKey: .netCashflow)
        try container.encode(openingBalance, forKey: .openingBalance)
        try container.encode(operatingCashflow, forKey: .operatingCashflow)
        try container.encode(period, forKey: .period)
    }
}

