//
// CategoryTotal.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CategoryTotal: Codable, JSONEncodable, Hashable {

    public var categoryId: String
    public var sharePct: Double
    public var tco2e: String

    public init(categoryId: String, sharePct: Double, tco2e: String) {
        self.categoryId = categoryId
        self.sharePct = sharePct
        self.tco2e = tco2e
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case categoryId = "category_id"
        case sharePct = "share_pct"
        case tco2e
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(categoryId, forKey: .categoryId)
        try container.encode(sharePct, forKey: .sharePct)
        try container.encode(tco2e, forKey: .tco2e)
    }
}

