//
// CommunicationChannel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Channel the communication took place on. */
public enum CommunicationChannel: String, Codable, CaseIterable {
    case email = "email"
    case call = "call"
    case meeting = "meeting"
    case chat = "chat"
    case note = "note"
}
