//
// CouponValidation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CouponValidation: Codable, JSONEncodable, Hashable {

    public var code: String
    public var discountType: String
    public var discountValue: String
    public var discountedAmount: String
    public var maxDiscountAmount: String?
    public var reason: String?
    public var valid: Bool

    public init(code: String, discountType: String, discountValue: String, discountedAmount: String, maxDiscountAmount: String? = nil, reason: String? = nil, valid: Bool) {
        self.code = code
        self.discountType = discountType
        self.discountValue = discountValue
        self.discountedAmount = discountedAmount
        self.maxDiscountAmount = maxDiscountAmount
        self.reason = reason
        self.valid = valid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case discountType = "discount_type"
        case discountValue = "discount_value"
        case discountedAmount = "discounted_amount"
        case maxDiscountAmount = "max_discount_amount"
        case reason
        case valid
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encode(discountType, forKey: .discountType)
        try container.encode(discountValue, forKey: .discountValue)
        try container.encode(discountedAmount, forKey: .discountedAmount)
        try container.encodeIfPresent(maxDiscountAmount, forKey: .maxDiscountAmount)
        try container.encodeIfPresent(reason, forKey: .reason)
        try container.encode(valid, forKey: .valid)
    }
}

