//
// Coupon.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Coupon: Codable, JSONEncodable, Hashable {

    public static let codeRule = StringRule(minLength: 1, maxLength: 50, pattern: nil)
    public static let descriptionRule = StringRule(minLength: nil, maxLength: 500, pattern: nil)
    public var code: String
    public var description: String?
    public var discountType: DiscountType
    public var discountValue: String
    public var expiresAt: Date?
    public var isActive: Bool?
    public var isCombineable: Bool?
    public var maxDiscountAmount: String?
    public var maxUses: Int?
    public var maxUsesPerCustomer: Int?
    public var minOrderAmount: String?
    public var productIds: AnyCodable?
    public var startsAt: Date?

    public init(code: String, description: String? = nil, discountType: DiscountType, discountValue: String, expiresAt: Date? = nil, isActive: Bool? = nil, isCombineable: Bool? = nil, maxDiscountAmount: String? = nil, maxUses: Int? = nil, maxUsesPerCustomer: Int? = nil, minOrderAmount: String? = nil, productIds: AnyCodable? = nil, startsAt: Date? = nil) {
        self.code = code
        self.description = description
        self.discountType = discountType
        self.discountValue = discountValue
        self.expiresAt = expiresAt
        self.isActive = isActive
        self.isCombineable = isCombineable
        self.maxDiscountAmount = maxDiscountAmount
        self.maxUses = maxUses
        self.maxUsesPerCustomer = maxUsesPerCustomer
        self.minOrderAmount = minOrderAmount
        self.productIds = productIds
        self.startsAt = startsAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case description
        case discountType
        case discountValue
        case expiresAt
        case isActive
        case isCombineable
        case maxDiscountAmount
        case maxUses
        case maxUsesPerCustomer
        case minOrderAmount
        case productIds
        case startsAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(discountType, forKey: .discountType)
        try container.encode(discountValue, forKey: .discountValue)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
        try container.encodeIfPresent(isActive, forKey: .isActive)
        try container.encodeIfPresent(isCombineable, forKey: .isCombineable)
        try container.encodeIfPresent(maxDiscountAmount, forKey: .maxDiscountAmount)
        try container.encodeIfPresent(maxUses, forKey: .maxUses)
        try container.encodeIfPresent(maxUsesPerCustomer, forKey: .maxUsesPerCustomer)
        try container.encodeIfPresent(minOrderAmount, forKey: .minOrderAmount)
        try container.encodeIfPresent(productIds, forKey: .productIds)
        try container.encodeIfPresent(startsAt, forKey: .startsAt)
    }
}

