//
// CreateSubscriptionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateSubscriptionRequest: Codable, JSONEncodable, Hashable {

    public var eventType: String
    public var isActive: Bool?
    public var name: String
    public var secret: String?
    public var url: String

    public init(eventType: String, isActive: Bool? = nil, name: String, secret: String? = nil, url: String) {
        self.eventType = eventType
        self.isActive = isActive
        self.name = name
        self.secret = secret
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventType = "event_type"
        case isActive = "is_active"
        case name
        case secret
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eventType, forKey: .eventType)
        try container.encodeIfPresent(isActive, forKey: .isActive)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(secret, forKey: .secret)
        try container.encode(url, forKey: .url)
    }
}

