//
// CreateChannelDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateChannelDto: Codable, JSONEncodable, Hashable {

    public var channelType: String
    public var config: AnyCodable?
    public var name: String

    public init(channelType: String, config: AnyCodable?, name: String) {
        self.channelType = channelType
        self.config = config
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case channelType = "channel_type"
        case config
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(channelType, forKey: .channelType)
        try container.encode(config, forKey: .config)
        try container.encode(name, forKey: .name)
    }
}

