//
// Customer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Customer: Codable, JSONEncodable, Hashable {

    public static let contactPersonRule = StringRule(minLength: nil, maxLength: 255, pattern: nil)
    public static let externalOrderNumberRule = StringRule(minLength: nil, maxLength: 100, pattern: nil)
    public static let nameRule = StringRule(minLength: 1, maxLength: 255, pattern: nil)
    public static let paymentGracePeriodDaysRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 365, exclusiveMaximum: false, multipleOf: nil)
    public static let phoneRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^\\+?[0-9\\s\\-\\(\\)]{7,20}$/")
    public static let vatIdRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^[A-Z]{2}[0-9A-Z]{8,15}$/")
    public var address: AnyCodable?
    public var contactPerson: String?
    public var email: String?
    public var externalOrderNumber: String?
    public var name: String
    public var paymentGracePeriodDays: Int?
    public var phone: String?
    public var vatId: String?

    public init(address: AnyCodable? = nil, contactPerson: String? = nil, email: String? = nil, externalOrderNumber: String? = nil, name: String, paymentGracePeriodDays: Int? = nil, phone: String? = nil, vatId: String? = nil) {
        self.address = address
        self.contactPerson = contactPerson
        self.email = email
        self.externalOrderNumber = externalOrderNumber
        self.name = name
        self.paymentGracePeriodDays = paymentGracePeriodDays
        self.phone = phone
        self.vatId = vatId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case contactPerson
        case email
        case externalOrderNumber
        case name
        case paymentGracePeriodDays
        case phone
        case vatId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(contactPerson, forKey: .contactPerson)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(externalOrderNumber, forKey: .externalOrderNumber)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(paymentGracePeriodDays, forKey: .paymentGracePeriodDays)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(vatId, forKey: .vatId)
    }
}

