//
// DeliveryAppointmentCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeliveryAppointmentCreate: Codable, JSONEncodable, Hashable {

    public var email: String
    public var notes: String?
    public var phone: String?
    public var requestedDate: Date
    /** One of: requested | confirmed | arrived | cancelled | completed */
    public var status: DeliveryAppointmentStatus
    public var supplierName: String
    /** e.g. \"08:00-10:00\" */
    public var timeSlot: String?
    /** References the warehouse entity. */
    public var warehouseId: String

    public init(email: String, notes: String? = nil, phone: String? = nil, requestedDate: Date, status: DeliveryAppointmentStatus, supplierName: String, timeSlot: String? = nil, warehouseId: String) {
        self.email = email
        self.notes = notes
        self.phone = phone
        self.requestedDate = requestedDate
        self.status = status
        self.supplierName = supplierName
        self.timeSlot = timeSlot
        self.warehouseId = warehouseId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case notes
        case phone
        case requestedDate
        case status
        case supplierName
        case timeSlot
        case warehouseId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encode(requestedDate, forKey: .requestedDate)
        try container.encode(status, forKey: .status)
        try container.encode(supplierName, forKey: .supplierName)
        try container.encodeIfPresent(timeSlot, forKey: .timeSlot)
        try container.encode(warehouseId, forKey: .warehouseId)
    }
}

