//
// DeliveryNote.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeliveryNote: Codable, JSONEncodable, Hashable {

    public var address: AnyCodable?
    /** References the contact entity. */
    public var contactId: String?
    public var contactName: String?
    public var currency: String
    public var deliveryDate: Date?
    public var deliveryNoteNumber: String?
    public var files: AnyCodable?
    public var introduction: String?
    public var lineItems: AnyCodable?
    /** References the preceding sales voucher entity. */
    public var precedingSalesVoucherId: String?
    public var precedingSalesVoucherType: PrecedingSalesVoucherType?
    public var remark: String?
    public var shippingDate: Date?
    public var shippingMethod: String?
    public var subtotal: String?
    public var title: String?
    public var totalAmount: String?
    public var voucherDate: Date
    public var voucherStatus: VoucherStatus

    public init(address: AnyCodable? = nil, contactId: String? = nil, contactName: String? = nil, currency: String, deliveryDate: Date? = nil, deliveryNoteNumber: String? = nil, files: AnyCodable? = nil, introduction: String? = nil, lineItems: AnyCodable? = nil, precedingSalesVoucherId: String? = nil, precedingSalesVoucherType: PrecedingSalesVoucherType? = nil, remark: String? = nil, shippingDate: Date? = nil, shippingMethod: String? = nil, subtotal: String? = nil, title: String? = nil, totalAmount: String? = nil, voucherDate: Date, voucherStatus: VoucherStatus) {
        self.address = address
        self.contactId = contactId
        self.contactName = contactName
        self.currency = currency
        self.deliveryDate = deliveryDate
        self.deliveryNoteNumber = deliveryNoteNumber
        self.files = files
        self.introduction = introduction
        self.lineItems = lineItems
        self.precedingSalesVoucherId = precedingSalesVoucherId
        self.precedingSalesVoucherType = precedingSalesVoucherType
        self.remark = remark
        self.shippingDate = shippingDate
        self.shippingMethod = shippingMethod
        self.subtotal = subtotal
        self.title = title
        self.totalAmount = totalAmount
        self.voucherDate = voucherDate
        self.voucherStatus = voucherStatus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case contactId
        case contactName
        case currency
        case deliveryDate
        case deliveryNoteNumber
        case files
        case introduction
        case lineItems
        case precedingSalesVoucherId
        case precedingSalesVoucherType
        case remark
        case shippingDate
        case shippingMethod
        case subtotal
        case title
        case totalAmount
        case voucherDate
        case voucherStatus
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(contactId, forKey: .contactId)
        try container.encodeIfPresent(contactName, forKey: .contactName)
        try container.encode(currency, forKey: .currency)
        try container.encodeIfPresent(deliveryDate, forKey: .deliveryDate)
        try container.encodeIfPresent(deliveryNoteNumber, forKey: .deliveryNoteNumber)
        try container.encodeIfPresent(files, forKey: .files)
        try container.encodeIfPresent(introduction, forKey: .introduction)
        try container.encodeIfPresent(lineItems, forKey: .lineItems)
        try container.encodeIfPresent(precedingSalesVoucherId, forKey: .precedingSalesVoucherId)
        try container.encodeIfPresent(precedingSalesVoucherType, forKey: .precedingSalesVoucherType)
        try container.encodeIfPresent(remark, forKey: .remark)
        try container.encodeIfPresent(shippingDate, forKey: .shippingDate)
        try container.encodeIfPresent(shippingMethod, forKey: .shippingMethod)
        try container.encodeIfPresent(subtotal, forKey: .subtotal)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(totalAmount, forKey: .totalAmount)
        try container.encode(voucherDate, forKey: .voucherDate)
        try container.encode(voucherStatus, forKey: .voucherStatus)
    }
}

