//
// DhlCredentials.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DhlCredentials: Codable, JSONEncodable, Hashable {

    /** DHL-API-Key from developer.dhl.com (required for tracking). */
    public var apiKey: String
    /** Client credentials from the DHL developer app; required for label creation. */
    public var clientId: String?
    public var clientSecret: String?

    public init(apiKey: String, clientId: String? = nil, clientSecret: String? = nil) {
        self.apiKey = apiKey
        self.clientId = clientId
        self.clientSecret = clientSecret
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case apiKey = "api_key"
        case clientId = "client_id"
        case clientSecret = "client_secret"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(apiKey, forKey: .apiKey)
        try container.encodeIfPresent(clientId, forKey: .clientId)
        try container.encodeIfPresent(clientSecret, forKey: .clientSecret)
    }
}

