//
// EksErgebnis.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EksErgebnis: Codable, JSONEncodable, Hashable {

    public var gesamtergebnis: String
    public var monate: [EksMonatsWert]
    public var prognoseNaechste6Monate: String
    public var summeAusgaben: String
    public var summeEinnahmen: String
    public var zeitraumBis: String
    public var zeitraumVon: String

    public init(gesamtergebnis: String, monate: [EksMonatsWert], prognoseNaechste6Monate: String, summeAusgaben: String, summeEinnahmen: String, zeitraumBis: String, zeitraumVon: String) {
        self.gesamtergebnis = gesamtergebnis
        self.monate = monate
        self.prognoseNaechste6Monate = prognoseNaechste6Monate
        self.summeAusgaben = summeAusgaben
        self.summeEinnahmen = summeEinnahmen
        self.zeitraumBis = zeitraumBis
        self.zeitraumVon = zeitraumVon
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case gesamtergebnis
        case monate
        case prognoseNaechste6Monate = "prognose_naechste_6_monate"
        case summeAusgaben = "summe_ausgaben"
        case summeEinnahmen = "summe_einnahmen"
        case zeitraumBis = "zeitraum_bis"
        case zeitraumVon = "zeitraum_von"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(gesamtergebnis, forKey: .gesamtergebnis)
        try container.encode(monate, forKey: .monate)
        try container.encode(prognoseNaechste6Monate, forKey: .prognoseNaechste6Monate)
        try container.encode(summeAusgaben, forKey: .summeAusgaben)
        try container.encode(summeEinnahmen, forKey: .summeEinnahmen)
        try container.encode(zeitraumBis, forKey: .zeitraumBis)
        try container.encode(zeitraumVon, forKey: .zeitraumVon)
    }
}

