//
// EksMonatsWert.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EksMonatsWert: Codable, JSONEncodable, Hashable {

    public var ausgaben: String
    public var einnahmen: String
    public var ergebnis: String
    public var monat: String

    public init(ausgaben: String, einnahmen: String, ergebnis: String, monat: String) {
        self.ausgaben = ausgaben
        self.einnahmen = einnahmen
        self.ergebnis = ergebnis
        self.monat = monat
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ausgaben
        case einnahmen
        case ergebnis
        case monat
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ausgaben, forKey: .ausgaben)
        try container.encode(einnahmen, forKey: .einnahmen)
        try container.encode(ergebnis, forKey: .ergebnis)
        try container.encode(monat, forKey: .monat)
    }
}

