//
// EmissionFactorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EmissionFactorResponse: Codable, JSONEncodable, Hashable {

    public var categoryId: String
    public var kgCo2ePerUnit: Double
    public var nameDe: String
    public var source: String
    public var unit: String
    public var version: String

    public init(categoryId: String, kgCo2ePerUnit: Double, nameDe: String, source: String, unit: String, version: String) {
        self.categoryId = categoryId
        self.kgCo2ePerUnit = kgCo2ePerUnit
        self.nameDe = nameDe
        self.source = source
        self.unit = unit
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case categoryId = "category_id"
        case kgCo2ePerUnit = "kg_co2e_per_unit"
        case nameDe = "name_de"
        case source
        case unit
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(categoryId, forKey: .categoryId)
        try container.encode(kgCo2ePerUnit, forKey: .kgCo2ePerUnit)
        try container.encode(nameDe, forKey: .nameDe)
        try container.encode(source, forKey: .source)
        try container.encode(unit, forKey: .unit)
        try container.encode(version, forKey: .version)
    }
}

