//
// EmissionsReport.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EmissionsReport: Codable, JSONEncodable, Hashable {

    public var byCategory: [CategoryTotal]
    public var byScope: [ScopeTotal]
    public var byYear: [YearTotal]
    public var dataQuality: DataQuality
    public var intensityPerEmployee: Double?
    /** tCO2e per million EUR net revenue. */
    public var intensityPerRevenueMio: Double?
    /** Sum of paid/sent/partially-paid invoices (EUR net) in the year. */
    public var netRevenue: Double?
    /** Spend-based estimate from bookkeeping payments (EXIOBASE factor). */
    public var spendBasedEstimateTco2e: Double?
    public var targets: [TargetProgress]
    public var totalTco2e: String

    public init(byCategory: [CategoryTotal], byScope: [ScopeTotal], byYear: [YearTotal], dataQuality: DataQuality, intensityPerEmployee: Double? = nil, intensityPerRevenueMio: Double? = nil, netRevenue: Double? = nil, spendBasedEstimateTco2e: Double? = nil, targets: [TargetProgress], totalTco2e: String) {
        self.byCategory = byCategory
        self.byScope = byScope
        self.byYear = byYear
        self.dataQuality = dataQuality
        self.intensityPerEmployee = intensityPerEmployee
        self.intensityPerRevenueMio = intensityPerRevenueMio
        self.netRevenue = netRevenue
        self.spendBasedEstimateTco2e = spendBasedEstimateTco2e
        self.targets = targets
        self.totalTco2e = totalTco2e
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case byCategory = "by_category"
        case byScope = "by_scope"
        case byYear = "by_year"
        case dataQuality = "data_quality"
        case intensityPerEmployee = "intensity_per_employee"
        case intensityPerRevenueMio = "intensity_per_revenue_mio"
        case netRevenue = "net_revenue"
        case spendBasedEstimateTco2e = "spend_based_estimate_tco2e"
        case targets
        case totalTco2e = "total_tco2e"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(byCategory, forKey: .byCategory)
        try container.encode(byScope, forKey: .byScope)
        try container.encode(byYear, forKey: .byYear)
        try container.encode(dataQuality, forKey: .dataQuality)
        try container.encodeIfPresent(intensityPerEmployee, forKey: .intensityPerEmployee)
        try container.encodeIfPresent(intensityPerRevenueMio, forKey: .intensityPerRevenueMio)
        try container.encodeIfPresent(netRevenue, forKey: .netRevenue)
        try container.encodeIfPresent(spendBasedEstimateTco2e, forKey: .spendBasedEstimateTco2e)
        try container.encode(targets, forKey: .targets)
        try container.encode(totalTco2e, forKey: .totalTco2e)
    }
}

