//
// EmployeeStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Employment status. */
public enum EmployeeStatus: String, Codable, CaseIterable {
    case active = "active"
    case inactive = "inactive"
    case terminated = "terminated"
}
