//
// ExecutionStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Recurring template execution status. */
public enum ExecutionStatus: String, Codable, CaseIterable {
    case active = "ACTIVE"
    case paused = "PAUSED"
    case completed = "COMPLETED"
}
