//
// FeatureSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Feature toggles for a tenant. */
public struct FeatureSettings: Codable, JSONEncodable, Hashable {

    /** Online shop / storefront module (default: enabled). */
    public var onlineshop: Bool
    /** Bilanz (balance sheet) report. */
    public var reportBilanz: Bool
    /** BWA (betriebswirtschaftliche Auswertung). */
    public var reportBwa: Bool
    /** EÜR (Einnahmen-Überschuss-Rechnung). */
    public var reportEuer: Bool
    /** Gewerbesteuer report. */
    public var reportGewerbesteuer: Bool
    /** GuV (profit & loss) report. */
    public var reportGuv: Bool
    /** KSt (Körperschaftsteuer) report. */
    public var reportKst: Bool
    /** UStVA (Umsatzsteuervoranmeldung). */
    public var reportUstva: Bool

    public init(onlineshop: Bool, reportBilanz: Bool, reportBwa: Bool, reportEuer: Bool, reportGewerbesteuer: Bool, reportGuv: Bool, reportKst: Bool, reportUstva: Bool) {
        self.onlineshop = onlineshop
        self.reportBilanz = reportBilanz
        self.reportBwa = reportBwa
        self.reportEuer = reportEuer
        self.reportGewerbesteuer = reportGewerbesteuer
        self.reportGuv = reportGuv
        self.reportKst = reportKst
        self.reportUstva = reportUstva
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case onlineshop
        case reportBilanz
        case reportBwa
        case reportEuer
        case reportGewerbesteuer
        case reportGuv
        case reportKst
        case reportUstva
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(onlineshop, forKey: .onlineshop)
        try container.encode(reportBilanz, forKey: .reportBilanz)
        try container.encode(reportBwa, forKey: .reportBwa)
        try container.encode(reportEuer, forKey: .reportEuer)
        try container.encode(reportGewerbesteuer, forKey: .reportGewerbesteuer)
        try container.encode(reportGuv, forKey: .reportGuv)
        try container.encode(reportKst, forKey: .reportKst)
        try container.encode(reportUstva, forKey: .reportUstva)
    }
}

