//
// GdprApiKey.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GdprApiKey: Codable, JSONEncodable, Hashable {

    public var createdAt: Date
    public var expiresAt: Date?
    public var id: UUID
    public var keyId: UUID
    public var name: String
    public var revoked: Bool

    public init(createdAt: Date, expiresAt: Date? = nil, id: UUID, keyId: UUID, name: String, revoked: Bool) {
        self.createdAt = createdAt
        self.expiresAt = expiresAt
        self.id = id
        self.keyId = keyId
        self.name = name
        self.revoked = revoked
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAt
        case expiresAt
        case id
        case keyId
        case name
        case revoked
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
        try container.encode(id, forKey: .id)
        try container.encode(keyId, forKey: .keyId)
        try container.encode(name, forKey: .name)
        try container.encode(revoked, forKey: .revoked)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension GdprApiKey: Identifiable {}
