//
// GewinnverwendungsZeile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GewinnverwendungsZeile: Codable, JSONEncodable, Hashable {

    /** Betrag in EUR (2 Nachkommastellen, als String formatiert). */
    public var betrag: String
    /** Deutsche Bezeichnung der Zeile. */
    public var label: String

    public init(betrag: String, label: String) {
        self.betrag = betrag
        self.label = label
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case betrag
        case label
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(betrag, forKey: .betrag)
        try container.encode(label, forKey: .label)
    }
}

