//
// GroupFigureCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GroupFigureCreate: Codable, JSONEncodable, Hashable {

    public static let parentNameRule = StringRule(minLength: nil, maxLength: 200, pattern: nil)
    public static let parentSitusRule = StringRule(minLength: nil, maxLength: 100, pattern: nil)
    /** Bilanzsumme in EUR (§ 293 Abs. 1 Nr. 1 HGB). */
    public var bilanzsumme: String?
    /** § 291-Befreiung in Anspruch genommen. */
    public var exemptionClaimed: Bool?
    /** Durchschnittliche Arbeitnehmerzahl (§ 293 Abs. 1 Nr. 3 HGB). */
    public var mitarbeiter: Int64?
    /** Netto-Umsatzerlöse in EUR (§ 293 Abs. 1 Nr. 2 HGB). */
    public var nettoUmsatz: String?
    /** Name des Mutterunternehmens (§ 291 HGB, Zwischenholding). */
    public var parentName: String?
    /** Sitz des Mutterunternehmens, z. B. \"EU/EWR\" (§ 291 HGB). */
    public var parentSitus: String?

    public init(bilanzsumme: String? = nil, exemptionClaimed: Bool? = nil, mitarbeiter: Int64? = nil, nettoUmsatz: String? = nil, parentName: String? = nil, parentSitus: String? = nil) {
        self.bilanzsumme = bilanzsumme
        self.exemptionClaimed = exemptionClaimed
        self.mitarbeiter = mitarbeiter
        self.nettoUmsatz = nettoUmsatz
        self.parentName = parentName
        self.parentSitus = parentSitus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bilanzsumme
        case exemptionClaimed
        case mitarbeiter
        case nettoUmsatz
        case parentName
        case parentSitus
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(bilanzsumme, forKey: .bilanzsumme)
        try container.encodeIfPresent(exemptionClaimed, forKey: .exemptionClaimed)
        try container.encodeIfPresent(mitarbeiter, forKey: .mitarbeiter)
        try container.encodeIfPresent(nettoUmsatz, forKey: .nettoUmsatz)
        try container.encodeIfPresent(parentName, forKey: .parentName)
        try container.encodeIfPresent(parentSitus, forKey: .parentSitus)
    }
}

