//
// GuVItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GuVItem: Codable, JSONEncodable, Hashable {

    public var account: String
    public var amount: String
    public var name: String

    public init(account: String, amount: String, name: String) {
        self.account = account
        self.amount = amount
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case account
        case amount
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(account, forKey: .account)
        try container.encode(amount, forKey: .amount)
        try container.encode(name, forKey: .name)
    }
}

