//
// GuVReport.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GuVReport: Codable, JSONEncodable, Hashable {

    public var expenses: [GuVItem]
    public var generatedAt: String
    public var netIncome: String
    public var period: String
    public var revenue: [GuVItem]
    public var totalExpenses: String
    public var totalRevenue: String

    public init(expenses: [GuVItem], generatedAt: String, netIncome: String, period: String, revenue: [GuVItem], totalExpenses: String, totalRevenue: String) {
        self.expenses = expenses
        self.generatedAt = generatedAt
        self.netIncome = netIncome
        self.period = period
        self.revenue = revenue
        self.totalExpenses = totalExpenses
        self.totalRevenue = totalRevenue
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case expenses
        case generatedAt = "generated_at"
        case netIncome = "net_income"
        case period
        case revenue
        case totalExpenses = "total_expenses"
        case totalRevenue = "total_revenue"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(expenses, forKey: .expenses)
        try container.encode(generatedAt, forKey: .generatedAt)
        try container.encode(netIncome, forKey: .netIncome)
        try container.encode(period, forKey: .period)
        try container.encode(revenue, forKey: .revenue)
        try container.encode(totalExpenses, forKey: .totalExpenses)
        try container.encode(totalRevenue, forKey: .totalRevenue)
    }
}

