//
// IncomeStatement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IncomeStatement: Codable, JSONEncodable, Hashable {

    public var expenseItems: [PnLItem]
    public var netIncome: String
    public var revenueItems: [PnLItem]
    public var totalExpenses: String
    public var totalRevenue: String

    public init(expenseItems: [PnLItem], netIncome: String, revenueItems: [PnLItem], totalExpenses: String, totalRevenue: String) {
        self.expenseItems = expenseItems
        self.netIncome = netIncome
        self.revenueItems = revenueItems
        self.totalExpenses = totalExpenses
        self.totalRevenue = totalRevenue
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case expenseItems = "expense_items"
        case netIncome = "net_income"
        case revenueItems = "revenue_items"
        case totalExpenses = "total_expenses"
        case totalRevenue = "total_revenue"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(expenseItems, forKey: .expenseItems)
        try container.encode(netIncome, forKey: .netIncome)
        try container.encode(revenueItems, forKey: .revenueItems)
        try container.encode(totalExpenses, forKey: .totalExpenses)
        try container.encode(totalRevenue, forKey: .totalRevenue)
    }
}

