//
// InstituteCheckItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InstituteCheckItem: Codable, JSONEncodable, Hashable {

    public var exists: Bool
    public var name: String
    public var source: String

    public init(exists: Bool, name: String, source: String) {
        self.exists = exists
        self.name = name
        self.source = source
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case exists
        case name
        case source
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(exists, forKey: .exists)
        try container.encode(name, forKey: .name)
        try container.encode(source, forKey: .source)
    }
}

