//
// InvoiceMatchRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InvoiceMatchRequest: Codable, JSONEncodable, Hashable {

    public var supplierInvoiceId: String

    public init(supplierInvoiceId: String) {
        self.supplierInvoiceId = supplierInvoiceId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case supplierInvoiceId = "supplier_invoice_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(supplierInvoiceId, forKey: .supplierInvoiceId)
    }
}

