//
// JobStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Job queue status. */
public enum JobStatus: String, Codable, CaseIterable {
    case pending = "pending"
    case running = "running"
    case done = "done"
    case failed = "failed"
}
