//
// KontoReport.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct KontoReport: Codable, JSONEncodable, Hashable {

    public var generatedAt: String
    public var konten: [KontoItem]
    public var period: String

    public init(generatedAt: String, konten: [KontoItem], period: String) {
        self.generatedAt = generatedAt
        self.konten = konten
        self.period = period
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case generatedAt = "generated_at"
        case konten
        case period
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(generatedAt, forKey: .generatedAt)
        try container.encode(konten, forKey: .konten)
        try container.encode(period, forKey: .period)
    }
}

