//
// KonzernStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct KonzernStatus: Codable, JSONEncodable, Hashable {

    public var groessenbefreit: Bool
    public var kapitalmarktorientiert: Bool
    public var konzernabschlusspflicht: Bool
    /** Keine group_figures-Zeile für das Jahr vorhanden → keine Größenbefreiung. */
    public var missingGroupFigures: Bool
    /** Mutterunternehmen: mindestens eine beherrschte Beteiligung (§ 290 Abs. 1 HGB). */
    public var mutterunternehmen: Bool
    /** Mutterunternehmen für die Zwischenholding-Befreiung (§ 291 HGB). */
    public var parentName: String?
    public var parentSitus: String?
    public var participations: [KonzernBeteiligung]
    public var thresholds: KonzernThresholds
    public var year: Int
    public var zwischenholdingBefreit: Bool
    /** Hinweis zu den § 291-Voraussetzungen (EU/EWR-Sitz, geprüfter Konzernabschluss). */
    public var zwischenholdingHinweis: String?

    public init(groessenbefreit: Bool, kapitalmarktorientiert: Bool, konzernabschlusspflicht: Bool, missingGroupFigures: Bool, mutterunternehmen: Bool, parentName: String? = nil, parentSitus: String? = nil, participations: [KonzernBeteiligung], thresholds: KonzernThresholds, year: Int, zwischenholdingBefreit: Bool, zwischenholdingHinweis: String? = nil) {
        self.groessenbefreit = groessenbefreit
        self.kapitalmarktorientiert = kapitalmarktorientiert
        self.konzernabschlusspflicht = konzernabschlusspflicht
        self.missingGroupFigures = missingGroupFigures
        self.mutterunternehmen = mutterunternehmen
        self.parentName = parentName
        self.parentSitus = parentSitus
        self.participations = participations
        self.thresholds = thresholds
        self.year = year
        self.zwischenholdingBefreit = zwischenholdingBefreit
        self.zwischenholdingHinweis = zwischenholdingHinweis
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case groessenbefreit
        case kapitalmarktorientiert
        case konzernabschlusspflicht
        case missingGroupFigures = "missing_group_figures"
        case mutterunternehmen
        case parentName = "parent_name"
        case parentSitus = "parent_situs"
        case participations
        case thresholds
        case year
        case zwischenholdingBefreit = "zwischenholding_befreit"
        case zwischenholdingHinweis = "zwischenholding_hinweis"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(groessenbefreit, forKey: .groessenbefreit)
        try container.encode(kapitalmarktorientiert, forKey: .kapitalmarktorientiert)
        try container.encode(konzernabschlusspflicht, forKey: .konzernabschlusspflicht)
        try container.encode(missingGroupFigures, forKey: .missingGroupFigures)
        try container.encode(mutterunternehmen, forKey: .mutterunternehmen)
        try container.encodeIfPresent(parentName, forKey: .parentName)
        try container.encodeIfPresent(parentSitus, forKey: .parentSitus)
        try container.encode(participations, forKey: .participations)
        try container.encode(thresholds, forKey: .thresholds)
        try container.encode(year, forKey: .year)
        try container.encode(zwischenholdingBefreit, forKey: .zwischenholdingBefreit)
        try container.encodeIfPresent(zwischenholdingHinweis, forKey: .zwischenholdingHinweis)
    }
}

