//
// KstErgebnis.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct KstErgebnis: Codable, JSONEncodable, Hashable {

    public var gesamt: String
    public var gesamtbelastung: String
    public var gewerbesteuer: String
    public var gewinn: String
    public var istKapitalgesellschaft: Bool
    public var jahr: Int
    public var koerperschaftsteuer: String
    public var solidaritaetszuschlag: String

    public init(gesamt: String, gesamtbelastung: String, gewerbesteuer: String, gewinn: String, istKapitalgesellschaft: Bool, jahr: Int, koerperschaftsteuer: String, solidaritaetszuschlag: String) {
        self.gesamt = gesamt
        self.gesamtbelastung = gesamtbelastung
        self.gewerbesteuer = gewerbesteuer
        self.gewinn = gewinn
        self.istKapitalgesellschaft = istKapitalgesellschaft
        self.jahr = jahr
        self.koerperschaftsteuer = koerperschaftsteuer
        self.solidaritaetszuschlag = solidaritaetszuschlag
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case gesamt
        case gesamtbelastung
        case gewerbesteuer
        case gewinn
        case istKapitalgesellschaft = "ist_kapitalgesellschaft"
        case jahr
        case koerperschaftsteuer
        case solidaritaetszuschlag
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(gesamt, forKey: .gesamt)
        try container.encode(gesamtbelastung, forKey: .gesamtbelastung)
        try container.encode(gewerbesteuer, forKey: .gewerbesteuer)
        try container.encode(gewinn, forKey: .gewinn)
        try container.encode(istKapitalgesellschaft, forKey: .istKapitalgesellschaft)
        try container.encode(jahr, forKey: .jahr)
        try container.encode(koerperschaftsteuer, forKey: .koerperschaftsteuer)
        try container.encode(solidaritaetszuschlag, forKey: .solidaritaetszuschlag)
    }
}

