//
// LegalDocumentReset.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Optional filter for &#x60;POST /api/v1/legal/documents/reset&#x60;; empty body restores every document of the tenant. */
public struct LegalDocumentReset: Codable, JSONEncodable, Hashable {

    public var docType: String?
    public var lang: String?

    public init(docType: String? = nil, lang: String? = nil) {
        self.docType = docType
        self.lang = lang
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case docType
        case lang
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(docType, forKey: .docType)
        try container.encodeIfPresent(lang, forKey: .lang)
    }
}

