//
// LegalDocument.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LegalDocument: Codable, JSONEncodable, Hashable {

    /** Plain text, `\\n\\n` separates paragraphs. */
    public var content: String
    public var docType: LegalDocType
    public var lang: LanguageCode
    public var title: String

    public init(content: String, docType: LegalDocType, lang: LanguageCode, title: String) {
        self.content = content
        self.docType = docType
        self.lang = lang
        self.title = title
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case content
        case docType
        case lang
        case title
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(content, forKey: .content)
        try container.encode(docType, forKey: .docType)
        try container.encode(lang, forKey: .lang)
        try container.encode(title, forKey: .title)
    }
}

