//
// MessageType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Body format of a ticket message. */
public enum MessageType: String, Codable, CaseIterable {
    case text = "text"
    case html = "html"
}
