//
// NotificationDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Wire shape of a notification row (mirrors frontend Notification type). */
public struct NotificationDto: Codable, JSONEncodable, Hashable {

    public var createdAt: Date
    public var id: UUID
    public var isRead: Bool
    public var message: String?
    public var sentViaEmail: Bool
    public var tenantId: UUID
    public var title: String
    public var userId: UUID

    public init(createdAt: Date, id: UUID, isRead: Bool, message: String? = nil, sentViaEmail: Bool, tenantId: UUID, title: String, userId: UUID) {
        self.createdAt = createdAt
        self.id = id
        self.isRead = isRead
        self.message = message
        self.sentViaEmail = sentViaEmail
        self.tenantId = tenantId
        self.title = title
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAt = "created_at"
        case id
        case isRead = "is_read"
        case message
        case sentViaEmail = "sent_via_email"
        case tenantId = "tenant_id"
        case title
        case userId = "user_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(id, forKey: .id)
        try container.encode(isRead, forKey: .isRead)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encode(sentViaEmail, forKey: .sentViaEmail)
        try container.encode(tenantId, forKey: .tenantId)
        try container.encode(title, forKey: .title)
        try container.encode(userId, forKey: .userId)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension NotificationDto: Identifiable {}
