//
// OpenItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OpenItem: Codable, JSONEncodable, Hashable {

    public var amountDue: String
    public var amountPaid: String
    public var customerId: String?
    public var daysOverdue: Int64?
    public var dueDate: String?
    public var invoiceId: String
    public var invoiceNumber: String
    public var issueDate: String
    public var openAmount: String
    public var reminderLevel: ReminderLevel

    public init(amountDue: String, amountPaid: String, customerId: String? = nil, daysOverdue: Int64? = nil, dueDate: String? = nil, invoiceId: String, invoiceNumber: String, issueDate: String, openAmount: String, reminderLevel: ReminderLevel) {
        self.amountDue = amountDue
        self.amountPaid = amountPaid
        self.customerId = customerId
        self.daysOverdue = daysOverdue
        self.dueDate = dueDate
        self.invoiceId = invoiceId
        self.invoiceNumber = invoiceNumber
        self.issueDate = issueDate
        self.openAmount = openAmount
        self.reminderLevel = reminderLevel
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amountDue = "amount_due"
        case amountPaid = "amount_paid"
        case customerId = "customer_id"
        case daysOverdue = "days_overdue"
        case dueDate = "due_date"
        case invoiceId = "invoice_id"
        case invoiceNumber = "invoice_number"
        case issueDate = "issue_date"
        case openAmount = "open_amount"
        case reminderLevel = "reminder_level"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amountDue, forKey: .amountDue)
        try container.encode(amountPaid, forKey: .amountPaid)
        try container.encodeIfPresent(customerId, forKey: .customerId)
        try container.encodeIfPresent(daysOverdue, forKey: .daysOverdue)
        try container.encodeIfPresent(dueDate, forKey: .dueDate)
        try container.encode(invoiceId, forKey: .invoiceId)
        try container.encode(invoiceNumber, forKey: .invoiceNumber)
        try container.encode(issueDate, forKey: .issueDate)
        try container.encode(openAmount, forKey: .openAmount)
        try container.encode(reminderLevel, forKey: .reminderLevel)
    }
}

