//
// OrderStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum OrderStatus: String, Codable, CaseIterable {
    case pending = "pending"
    case ordered = "ordered"
    case confirmed = "confirmed"
    case processing = "processing"
    case paid = "paid"
    case shipped = "shipped"
    case completed = "completed"
    case closed = "closed"
    case cancelled = "cancelled"
    case refunded = "refunded"
    case failed = "failed"
}
