//
// PackingCompleteResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PackingCompleteResponse: Codable, JSONEncodable, Hashable {

    public var message: String
    public var newState: String
    public var orderNumber: String
    public var success: Bool

    public init(message: String, newState: String, orderNumber: String, success: Bool) {
        self.message = message
        self.newState = newState
        self.orderNumber = orderNumber
        self.success = success
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case newState = "new_state"
        case orderNumber = "order_number"
        case success
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
        try container.encode(newState, forKey: .newState)
        try container.encode(orderNumber, forKey: .orderNumber)
        try container.encode(success, forKey: .success)
    }
}

