//
// PackingVideoResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PackingVideoResponse: Codable, JSONEncodable, Hashable {

    public var message: String
    public var recordingUrl: String?
    public var success: Bool

    public init(message: String, recordingUrl: String? = nil, success: Bool) {
        self.message = message
        self.recordingUrl = recordingUrl
        self.success = success
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case recordingUrl = "recording_url"
        case success
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
        try container.encodeIfPresent(recordingUrl, forKey: .recordingUrl)
        try container.encode(success, forKey: .success)
    }
}

