//
// PartialFeatureSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Partial feature toggles: &#x60;None&#x60; keeps the company-type default, &#x60;Some&#x60; overrides it. */
public struct PartialFeatureSettings: Codable, JSONEncodable, Hashable {

    public var onlineshop: Bool?
    public var reportBilanz: Bool?
    public var reportBwa: Bool?
    public var reportEuer: Bool?
    public var reportGewerbesteuer: Bool?
    public var reportGuv: Bool?
    public var reportKst: Bool?
    public var reportUstva: Bool?

    public init(onlineshop: Bool? = nil, reportBilanz: Bool? = nil, reportBwa: Bool? = nil, reportEuer: Bool? = nil, reportGewerbesteuer: Bool? = nil, reportGuv: Bool? = nil, reportKst: Bool? = nil, reportUstva: Bool? = nil) {
        self.onlineshop = onlineshop
        self.reportBilanz = reportBilanz
        self.reportBwa = reportBwa
        self.reportEuer = reportEuer
        self.reportGewerbesteuer = reportGewerbesteuer
        self.reportGuv = reportGuv
        self.reportKst = reportKst
        self.reportUstva = reportUstva
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case onlineshop
        case reportBilanz
        case reportBwa
        case reportEuer
        case reportGewerbesteuer
        case reportGuv
        case reportKst
        case reportUstva
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(onlineshop, forKey: .onlineshop)
        try container.encodeIfPresent(reportBilanz, forKey: .reportBilanz)
        try container.encodeIfPresent(reportBwa, forKey: .reportBwa)
        try container.encodeIfPresent(reportEuer, forKey: .reportEuer)
        try container.encodeIfPresent(reportGewerbesteuer, forKey: .reportGewerbesteuer)
        try container.encodeIfPresent(reportGuv, forKey: .reportGuv)
        try container.encodeIfPresent(reportKst, forKey: .reportKst)
        try container.encodeIfPresent(reportUstva, forKey: .reportUstva)
    }
}

