//
// PaymentCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PaymentCreate: Codable, JSONEncodable, Hashable {

    public var amount: String?
    public var attachment: AnyCodable?
    public var currency: String?
    /** References the customer entity. */
    public var customerId: String?
    public var description: String?
    public var metadata: AnyCodable?
    public var method: PaymentMethod?
    public var paymentDate: Date?
    public var reference: String?

    public init(amount: String? = nil, attachment: AnyCodable? = nil, currency: String? = nil, customerId: String? = nil, description: String? = nil, metadata: AnyCodable? = nil, method: PaymentMethod? = nil, paymentDate: Date? = nil, reference: String? = nil) {
        self.amount = amount
        self.attachment = attachment
        self.currency = currency
        self.customerId = customerId
        self.description = description
        self.metadata = metadata
        self.method = method
        self.paymentDate = paymentDate
        self.reference = reference
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case attachment
        case currency
        case customerId
        case description
        case metadata
        case method
        case paymentDate
        case reference
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encodeIfPresent(attachment, forKey: .attachment)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(customerId, forKey: .customerId)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(method, forKey: .method)
        try container.encodeIfPresent(paymentDate, forKey: .paymentDate)
        try container.encodeIfPresent(reference, forKey: .reference)
    }
}

