//
// PayrollMonth.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PayrollMonth: Codable, JSONEncodable, Hashable {

    public static let monthRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var gross: String
    public var month: Int
    public var net: String

    public init(gross: String, month: Int, net: String) {
        self.gross = gross
        self.month = month
        self.net = net
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case gross
        case month
        case net
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(gross, forKey: .gross)
        try container.encode(month, forKey: .month)
        try container.encode(net, forKey: .net)
    }
}

