//
// PlanFeatures.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Feature flags per plan. */
public struct PlanFeatures: Codable, JSONEncodable, Hashable {

    public var connectors: Bool
    public var erp: Bool
    public var fancyReports: Bool
    public var taxAutomations: Bool

    public init(connectors: Bool, erp: Bool, fancyReports: Bool, taxAutomations: Bool) {
        self.connectors = connectors
        self.erp = erp
        self.fancyReports = fancyReports
        self.taxAutomations = taxAutomations
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case connectors
        case erp
        case fancyReports
        case taxAutomations
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(connectors, forKey: .connectors)
        try container.encode(erp, forKey: .erp)
        try container.encode(fancyReports, forKey: .fancyReports)
        try container.encode(taxAutomations, forKey: .taxAutomations)
    }
}

