//
// PlatformInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Public metadata for one registered plugin (admin UI). Maps 1:1 from [&#x60;plugin_core::PluginInfo&#x60;] (same field shape as before). */
public struct PlatformInfo: Codable, JSONEncodable, Hashable {

    public var author: String
    public var changelog: [ChangelogEntry]
    public var configFieldNames: [String]
    public var configFields: [ConfigFieldInfo]
    public var displayName: String
    public var platform: String
    public var pricing: PluginPricing
    public var supportedEntities: [String]
    public var supportsExport: Bool
    public var supportsImport: Bool
    public var supportsOauth: Bool
    public var version: String

    public init(author: String, changelog: [ChangelogEntry], configFieldNames: [String], configFields: [ConfigFieldInfo], displayName: String, platform: String, pricing: PluginPricing, supportedEntities: [String], supportsExport: Bool, supportsImport: Bool, supportsOauth: Bool, version: String) {
        self.author = author
        self.changelog = changelog
        self.configFieldNames = configFieldNames
        self.configFields = configFields
        self.displayName = displayName
        self.platform = platform
        self.pricing = pricing
        self.supportedEntities = supportedEntities
        self.supportsExport = supportsExport
        self.supportsImport = supportsImport
        self.supportsOauth = supportsOauth
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case author
        case changelog
        case configFieldNames = "config_field_names"
        case configFields = "config_fields"
        case displayName = "display_name"
        case platform
        case pricing
        case supportedEntities = "supported_entities"
        case supportsExport = "supports_export"
        case supportsImport = "supports_import"
        case supportsOauth = "supports_oauth"
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(author, forKey: .author)
        try container.encode(changelog, forKey: .changelog)
        try container.encode(configFieldNames, forKey: .configFieldNames)
        try container.encode(configFields, forKey: .configFields)
        try container.encode(displayName, forKey: .displayName)
        try container.encode(platform, forKey: .platform)
        try container.encode(pricing, forKey: .pricing)
        try container.encode(supportedEntities, forKey: .supportedEntities)
        try container.encode(supportsExport, forKey: .supportsExport)
        try container.encode(supportsImport, forKey: .supportsImport)
        try container.encode(supportsOauth, forKey: .supportsOauth)
        try container.encode(version, forKey: .version)
    }
}

