//
// PlausibilitySummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PlausibilitySummary: Codable, JSONEncodable, Hashable {

    public static let errorsRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let passedRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let totalChecksRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let warningsRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var errors: Int
    public var overallStatus: CheckStatus
    public var passed: Int
    public var totalChecks: Int
    public var warnings: Int

    public init(errors: Int, overallStatus: CheckStatus, passed: Int, totalChecks: Int, warnings: Int) {
        self.errors = errors
        self.overallStatus = overallStatus
        self.passed = passed
        self.totalChecks = totalChecks
        self.warnings = warnings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case errors
        case overallStatus = "overall_status"
        case passed
        case totalChecks = "total_checks"
        case warnings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(errors, forKey: .errors)
        try container.encode(overallStatus, forKey: .overallStatus)
        try container.encode(passed, forKey: .passed)
        try container.encode(totalChecks, forKey: .totalChecks)
        try container.encode(warnings, forKey: .warnings)
    }
}

