//
// PluginErrorOneOf2.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PluginErrorOneOf2: Codable, JSONEncodable, Hashable {

    public static let unauthorizedRule = ArrayRule(minItems: 2, maxItems: 2, uniqueItems: false)
    public var unauthorized: [AnyCodable]

    public init(unauthorized: [AnyCodable]) {
        self.unauthorized = unauthorized
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case unauthorized = "Unauthorized"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(unauthorized, forKey: .unauthorized)
    }
}

