//
// PluginErrorOneOf1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PluginErrorOneOf1: Codable, JSONEncodable, Hashable {

    public static let notFoundRule = ArrayRule(minItems: 2, maxItems: 2, uniqueItems: false)
    public var notFound: [AnyCodable]

    public init(notFound: [AnyCodable]) {
        self.notFound = notFound
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case notFound = "NotFound"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(notFound, forKey: .notFound)
    }
}

