//
// PluginPricingOneOf1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PluginPricingOneOf1: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case oneTime = "one_time"
    }
    public var price: Double
    public var type: ModelType

    public init(price: Double, type: ModelType) {
        self.price = price
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case price
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(price, forKey: .price)
        try container.encode(type, forKey: .type)
    }
}

