//
// PosRegisterStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** POS register status. */
public enum PosRegisterStatus: String, Codable, CaseIterable {
    case active = "active"
    case disabled = "disabled"
}
