//
// PosTableStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** POS table status. */
public enum PosTableStatus: String, Codable, CaseIterable {
    case free = "free"
    case occupied = "occupied"
}
