//
// PosTableCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PosTableCreate: Codable, JSONEncodable, Hashable {

    public static let nameRule = StringRule(minLength: 1, maxLength: 50, pattern: nil)
    public var currentOrderNumber: String?
    public var name: String
    public var status: PosTableStatus?

    public init(currentOrderNumber: String? = nil, name: String, status: PosTableStatus? = nil) {
        self.currentOrderNumber = currentOrderNumber
        self.name = name
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currentOrderNumber
        case name
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(currentOrderNumber, forKey: .currentOrderNumber)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

