//
// PrecedingSalesVoucherType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Type of the sales voucher that preceded this document. */
public enum PrecedingSalesVoucherType: String, Codable, CaseIterable {
    case orderConfirmation = "order_confirmation"
    case quotation = "quotation"
    case proformaInvoice = "proforma_invoice"
}
