//
// ProductionOrderCosting.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Actual-costing (Nachkalkulation) report for a production order. */
public struct ProductionOrderCosting: Codable, JSONEncodable, Hashable {

    /** material_cost_total ÷ quantity. */
    public var costPerUnit: String
    /** \"actual\" when costed from stock-movement consumption, else \"planned\". */
    public var costSource: String
    public var lines: [CostingLine]
    /** sale_price − cost_per_unit. */
    public var marginPerUnit: String?
    /** margin_per_unit ÷ cost_per_unit as a percentage. */
    public var marginPercent: String?
    /** Total material cost for the whole order. */
    public var materialCostTotal: String
    public var orderNumber: String
    public var productionOrderId: UUID
    public var quantity: Int64
    /** Finished product's sale price per unit (used to compute margin). */
    public var salePrice: String?
    public var status: String

    public init(costPerUnit: String, costSource: String, lines: [CostingLine], marginPerUnit: String? = nil, marginPercent: String? = nil, materialCostTotal: String, orderNumber: String, productionOrderId: UUID, quantity: Int64, salePrice: String? = nil, status: String) {
        self.costPerUnit = costPerUnit
        self.costSource = costSource
        self.lines = lines
        self.marginPerUnit = marginPerUnit
        self.marginPercent = marginPercent
        self.materialCostTotal = materialCostTotal
        self.orderNumber = orderNumber
        self.productionOrderId = productionOrderId
        self.quantity = quantity
        self.salePrice = salePrice
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case costPerUnit
        case costSource
        case lines
        case marginPerUnit
        case marginPercent
        case materialCostTotal
        case orderNumber
        case productionOrderId
        case quantity
        case salePrice
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(costPerUnit, forKey: .costPerUnit)
        try container.encode(costSource, forKey: .costSource)
        try container.encode(lines, forKey: .lines)
        try container.encodeIfPresent(marginPerUnit, forKey: .marginPerUnit)
        try container.encodeIfPresent(marginPercent, forKey: .marginPercent)
        try container.encode(materialCostTotal, forKey: .materialCostTotal)
        try container.encode(orderNumber, forKey: .orderNumber)
        try container.encode(productionOrderId, forKey: .productionOrderId)
        try container.encode(quantity, forKey: .quantity)
        try container.encodeIfPresent(salePrice, forKey: .salePrice)
        try container.encode(status, forKey: .status)
    }
}

