//
// ProductionOrderStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Production order status. */
public enum ProductionOrderStatus: String, Codable, CaseIterable {
    case planned = "planned"
    case inProduction = "in_production"
    case completed = "completed"
    case cancelled = "cancelled"
}
