//
// ProductCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProductCategory: Codable, JSONEncodable, Hashable {

    public var description: String?
    public var name: String
    /** References the category entity. */
    public var parentCategoryId: String?
    public var sortOrder: Int

    public init(description: String? = nil, name: String, parentCategoryId: String? = nil, sortOrder: Int) {
        self.description = description
        self.name = name
        self.parentCategoryId = parentCategoryId
        self.sortOrder = sortOrder
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case name
        case parentCategoryId
        case sortOrder
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(parentCategoryId, forKey: .parentCategoryId)
        try container.encode(sortOrder, forKey: .sortOrder)
    }
}

