//
// ProformaInvoiceCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProformaInvoiceCreate: Codable, JSONEncodable, Hashable {

    public var convertedAt: Date?
    /** Set when the proforma was converted into a real invoice. References the invoice entity. */
    public var convertedToInvoiceId: String?
    public var currency: CurrencyCode
    /** References the customer entity. */
    public var customerId: String?
    /** Snapshot of the recipient at issue time (address, VAT id, …). */
    public var customerSnapshot: AnyCodable?
    public var issueDate: Date
    public var lineItems: AnyCodable?
    public var notes: String?
    /** Reference to the order/quote this proforma belongs to. */
    public var orderNumber: String?
    /** Optional deadline the real invoice should carry after conversion. */
    public var paymentDueDate: Date?
    /** References the quotation entity. */
    public var quotationId: String?
    /** `draft` | `sent` | `converted`. */
    public var status: ProformaInvoiceStatus
    public var subtotal: String
    public var totalAmount: String
    public var totalTax: String

    public init(convertedAt: Date? = nil, convertedToInvoiceId: String? = nil, currency: CurrencyCode, customerId: String? = nil, customerSnapshot: AnyCodable? = nil, issueDate: Date, lineItems: AnyCodable?, notes: String? = nil, orderNumber: String? = nil, paymentDueDate: Date? = nil, quotationId: String? = nil, status: ProformaInvoiceStatus, subtotal: String, totalAmount: String, totalTax: String) {
        self.convertedAt = convertedAt
        self.convertedToInvoiceId = convertedToInvoiceId
        self.currency = currency
        self.customerId = customerId
        self.customerSnapshot = customerSnapshot
        self.issueDate = issueDate
        self.lineItems = lineItems
        self.notes = notes
        self.orderNumber = orderNumber
        self.paymentDueDate = paymentDueDate
        self.quotationId = quotationId
        self.status = status
        self.subtotal = subtotal
        self.totalAmount = totalAmount
        self.totalTax = totalTax
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case convertedAt
        case convertedToInvoiceId
        case currency
        case customerId
        case customerSnapshot
        case issueDate
        case lineItems
        case notes
        case orderNumber
        case paymentDueDate
        case quotationId
        case status
        case subtotal
        case totalAmount
        case totalTax
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(convertedAt, forKey: .convertedAt)
        try container.encodeIfPresent(convertedToInvoiceId, forKey: .convertedToInvoiceId)
        try container.encode(currency, forKey: .currency)
        try container.encodeIfPresent(customerId, forKey: .customerId)
        try container.encodeIfPresent(customerSnapshot, forKey: .customerSnapshot)
        try container.encode(issueDate, forKey: .issueDate)
        try container.encode(lineItems, forKey: .lineItems)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(orderNumber, forKey: .orderNumber)
        try container.encodeIfPresent(paymentDueDate, forKey: .paymentDueDate)
        try container.encodeIfPresent(quotationId, forKey: .quotationId)
        try container.encode(status, forKey: .status)
        try container.encode(subtotal, forKey: .subtotal)
        try container.encode(totalAmount, forKey: .totalAmount)
        try container.encode(totalTax, forKey: .totalTax)
    }
}

