//
// PublicDeliveryAppointmentStatusResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PublicDeliveryAppointmentStatusResponse: Codable, JSONEncodable, Hashable {

    public var appointmentId: String
    public var requestedDate: Date
    public var status: String
    public var timeSlot: String?
    public var warehouseName: String

    public init(appointmentId: String, requestedDate: Date, status: String, timeSlot: String? = nil, warehouseName: String) {
        self.appointmentId = appointmentId
        self.requestedDate = requestedDate
        self.status = status
        self.timeSlot = timeSlot
        self.warehouseName = warehouseName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case appointmentId
        case requestedDate
        case status
        case timeSlot
        case warehouseName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(appointmentId, forKey: .appointmentId)
        try container.encode(requestedDate, forKey: .requestedDate)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(timeSlot, forKey: .timeSlot)
        try container.encode(warehouseName, forKey: .warehouseName)
    }
}

