//
// PublicDeliveryAppointmentResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PublicDeliveryAppointmentResponse: Codable, JSONEncodable, Hashable {

    public var appointmentId: String
    /** Carries the status-check token (email is out of scope for now). */
    public var confirmationHint: String
    public var message: String
    public var status: String

    public init(appointmentId: String, confirmationHint: String, message: String, status: String) {
        self.appointmentId = appointmentId
        self.confirmationHint = confirmationHint
        self.message = message
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case appointmentId
        case confirmationHint
        case message
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(appointmentId, forKey: .appointmentId)
        try container.encode(confirmationHint, forKey: .confirmationHint)
        try container.encode(message, forKey: .message)
        try container.encode(status, forKey: .status)
    }
}

