//
// QuizQuestion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct QuizQuestion: Codable, JSONEncodable, Hashable {

    public var id: String
    public var options: [String]
    public var optionsEn: [String]
    public var question: String
    public var questionEn: String

    public init(id: String, options: [String], optionsEn: [String], question: String, questionEn: String) {
        self.id = id
        self.options = options
        self.optionsEn = optionsEn
        self.question = question
        self.questionEn = questionEn
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case options
        case optionsEn
        case question
        case questionEn
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(options, forKey: .options)
        try container.encode(optionsEn, forKey: .optionsEn)
        try container.encode(question, forKey: .question)
        try container.encode(questionEn, forKey: .questionEn)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension QuizQuestion: Identifiable {}
