//
// RecurringTemplate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RecurringTemplate: Codable, JSONEncodable, Hashable {

    public var createdAt: String
    public var deletedAt: String?
    public var endDate: Date?
    public var executionInterval: String
    public var executionStatus: String
    public var finalize: Bool
    public var lastExecutedAt: Date?
    public var name: String
    public var nextExecutionAt: Date?
    public var startDate: Date
    public var templateId: String
    public var templateType: String
    public var updatedAt: String?
    public var voucherData: AnyCodable?

    public init(createdAt: String, deletedAt: String? = nil, endDate: Date? = nil, executionInterval: String, executionStatus: String, finalize: Bool, lastExecutedAt: Date? = nil, name: String, nextExecutionAt: Date? = nil, startDate: Date, templateId: String, templateType: String, updatedAt: String? = nil, voucherData: AnyCodable?) {
        self.createdAt = createdAt
        self.deletedAt = deletedAt
        self.endDate = endDate
        self.executionInterval = executionInterval
        self.executionStatus = executionStatus
        self.finalize = finalize
        self.lastExecutedAt = lastExecutedAt
        self.name = name
        self.nextExecutionAt = nextExecutionAt
        self.startDate = startDate
        self.templateId = templateId
        self.templateType = templateType
        self.updatedAt = updatedAt
        self.voucherData = voucherData
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAt = "created_at"
        case deletedAt = "deleted_at"
        case endDate = "end_date"
        case executionInterval = "execution_interval"
        case executionStatus = "execution_status"
        case finalize
        case lastExecutedAt = "last_executed_at"
        case name
        case nextExecutionAt = "next_execution_at"
        case startDate = "start_date"
        case templateId = "template_id"
        case templateType = "template_type"
        case updatedAt = "updated_at"
        case voucherData = "voucher_data"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(deletedAt, forKey: .deletedAt)
        try container.encodeIfPresent(endDate, forKey: .endDate)
        try container.encode(executionInterval, forKey: .executionInterval)
        try container.encode(executionStatus, forKey: .executionStatus)
        try container.encode(finalize, forKey: .finalize)
        try container.encodeIfPresent(lastExecutedAt, forKey: .lastExecutedAt)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(nextExecutionAt, forKey: .nextExecutionAt)
        try container.encode(startDate, forKey: .startDate)
        try container.encode(templateId, forKey: .templateId)
        try container.encode(templateType, forKey: .templateType)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encode(voucherData, forKey: .voucherData)
    }
}

