//
// ReferenceType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Stock movement reference type. */
public enum ReferenceType: String, Codable, CaseIterable {
    case goodsReceipt = "goods_receipt"
    case productionOrder = "production_order"
    case transferIn = "transfer_in"
    case stockTransfer = "stock_transfer"
    case returnOrder = "return_order"
    case inventoryCount = "inventory_count"
}
