//
// ReturnWarehouseSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Aggregation for a single warehouse. */
public struct ReturnWarehouseSummary: Codable, JSONEncodable, Hashable {

    public static let returnsRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var itemsRestocked: Int64
    public var itemsScrapped: Int64
    public var returns: Int64
    public var warehouseId: String?

    public init(itemsRestocked: Int64, itemsScrapped: Int64, returns: Int64, warehouseId: String? = nil) {
        self.itemsRestocked = itemsRestocked
        self.itemsScrapped = itemsScrapped
        self.returns = returns
        self.warehouseId = warehouseId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case itemsRestocked
        case itemsScrapped
        case returns
        case warehouseId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(itemsRestocked, forKey: .itemsRestocked)
        try container.encode(itemsScrapped, forKey: .itemsScrapped)
        try container.encode(returns, forKey: .returns)
        try container.encodeIfPresent(warehouseId, forKey: .warehouseId)
    }
}

