//
// ReturnLogisticsSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Warehouse-level aggregation for the returns logistics dashboard. */
public struct ReturnLogisticsSummary: Codable, JSONEncodable, Hashable {

    public static let totalReturnsRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** Number of return orders per status. */
    public var byStatus: AnyCodable?
    /** Per-warehouse aggregation. */
    public var byWarehouse: [ReturnWarehouseSummary]
    /** Sum of `restock: true` line-item quantities. */
    public var itemsRestocked: Int64
    /** Sum of `restock: false` line-item quantities (scrapped/disposed). */
    public var itemsScrapped: Int64
    /** Sum of all line-item quantities across returns. */
    public var totalItems: Int64
    /** Total number of return orders (excluding soft-deleted). */
    public var totalReturns: Int64

    public init(byStatus: AnyCodable?, byWarehouse: [ReturnWarehouseSummary], itemsRestocked: Int64, itemsScrapped: Int64, totalItems: Int64, totalReturns: Int64) {
        self.byStatus = byStatus
        self.byWarehouse = byWarehouse
        self.itemsRestocked = itemsRestocked
        self.itemsScrapped = itemsScrapped
        self.totalItems = totalItems
        self.totalReturns = totalReturns
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case byStatus
        case byWarehouse
        case itemsRestocked
        case itemsScrapped
        case totalItems
        case totalReturns
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(byStatus, forKey: .byStatus)
        try container.encode(byWarehouse, forKey: .byWarehouse)
        try container.encode(itemsRestocked, forKey: .itemsRestocked)
        try container.encode(itemsScrapped, forKey: .itemsScrapped)
        try container.encode(totalItems, forKey: .totalItems)
        try container.encode(totalReturns, forKey: .totalReturns)
    }
}

