//
// RevenueItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RevenueItem: Codable, JSONEncodable, Hashable {

    public var amount: String
    public var category: String
    public var percentage: Double

    public init(amount: String, category: String, percentage: Double) {
        self.amount = amount
        self.category = category
        self.percentage = percentage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case category
        case percentage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amount, forKey: .amount)
        try container.encode(category, forKey: .category)
        try container.encode(percentage, forKey: .percentage)
    }
}

