//
// SepaDirectDebitResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SepaDirectDebitResponse: Codable, JSONEncodable, Hashable {

    public var contentType: String
    public var filename: String
    public var xmlContent: String

    public init(contentType: String, filename: String, xmlContent: String) {
        self.contentType = contentType
        self.filename = filename
        self.xmlContent = xmlContent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case contentType = "content_type"
        case filename
        case xmlContent = "xml_content"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(contentType, forKey: .contentType)
        try container.encode(filename, forKey: .filename)
        try container.encode(xmlContent, forKey: .xmlContent)
    }
}

