//
// ServiceJob.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceJob: Codable, JSONEncodable, Hashable {

    public static let addressRule = StringRule(minLength: 1, maxLength: 255, pattern: nil)
    public static let descriptionRule = StringRule(minLength: 1, maxLength: 1000, pattern: nil)
    public static let estimatedDurationMinutesRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 100000, exclusiveMaximum: false, multipleOf: nil)
    /** Street + zip + city of the job location. */
    public var address: String?
    /** Customer email for email notifications. */
    public var customerEmail: String?
    /** References the customer entity. */
    public var customerId: UUID?
    /** Denormalized customer name for quick display. */
    public var customerName: String?
    /** Customer phone for SMS notifications later. */
    public var customerPhone: String?
    /** What work needs to be done. */
    public var description: String?
    /** Estimated time for the job in minutes. */
    public var estimatedDurationMinutes: Int?
    /** Latitude for map display (OpenStreetMap). */
    public var lat: Double?
    /** Longitude for map display (OpenStreetMap). */
    public var lng: Double?
    public var notes: String?
    /** Dispatch status: \"pending\", \"assigned\", \"en_route\", \"in_progress\", \"completed\", \"cancelled\". */
    public var status: ServiceJobStatus?

    public init(address: String? = nil, customerEmail: String? = nil, customerId: UUID? = nil, customerName: String? = nil, customerPhone: String? = nil, description: String? = nil, estimatedDurationMinutes: Int? = nil, lat: Double? = nil, lng: Double? = nil, notes: String? = nil, status: ServiceJobStatus? = nil) {
        self.address = address
        self.customerEmail = customerEmail
        self.customerId = customerId
        self.customerName = customerName
        self.customerPhone = customerPhone
        self.description = description
        self.estimatedDurationMinutes = estimatedDurationMinutes
        self.lat = lat
        self.lng = lng
        self.notes = notes
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case customerEmail
        case customerId
        case customerName
        case customerPhone
        case description
        case estimatedDurationMinutes
        case lat
        case lng
        case notes
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(customerEmail, forKey: .customerEmail)
        try container.encodeIfPresent(customerId, forKey: .customerId)
        try container.encodeIfPresent(customerName, forKey: .customerName)
        try container.encodeIfPresent(customerPhone, forKey: .customerPhone)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(estimatedDurationMinutes, forKey: .estimatedDurationMinutes)
        try container.encodeIfPresent(lat, forKey: .lat)
        try container.encodeIfPresent(lng, forKey: .lng)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

