//
// SilentPartner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SilentPartner: Codable, JSONEncodable, Hashable {

    public static let nameRule = StringRule(minLength: 1, maxLength: 200, pattern: nil)
    public static let notesRule = StringRule(minLength: nil, maxLength: 500, pattern: nil)
    /** Datum des Vertragsabschlusses. */
    public var contractDate: Date?
    /** Einlage (§ 230 HGB). */
    public var einlage: String?
    /** Gewinnbeteiligungsquote in Prozent (§ 231 HGB). */
    public var gewinnquotePct: String?
    /** Nicht erhobene Gewinne (§ 232 Abs. 3 HGB). */
    public var gewinnvortrag: String?
    /** Instrument: \"typisch\" | \"atypisch\" | \"partiarisches_darlehen\" | \"genussrecht\". */
    public var instrumentType: InstrumentType
    /** 25 % Kapitalertragsteuer einbehalten (§ 43 Abs. 1 Nr. 3 EStG; typisch + partiarisches Darlehen). */
    public var kestPflichtig: Bool?
    /** Name des stillen Gesellschafters. */
    public var name: String?
    /** Freitext-Notizen. */
    public var notes: String?
    /** Kumulierte Verluste gegen die Einlage (§ 232 Abs. 2 HGB, ≤ Einlage). */
    public var verlustVerrechnungskonto: String?
    /** Verlustbeteiligung (§ 231 Abs. 2 HGB; kann ausgeschlossen werden). */
    public var verlustbeteiligung: Bool?

    public init(contractDate: Date? = nil, einlage: String? = nil, gewinnquotePct: String? = nil, gewinnvortrag: String? = nil, instrumentType: InstrumentType, kestPflichtig: Bool? = nil, name: String? = nil, notes: String? = nil, verlustVerrechnungskonto: String? = nil, verlustbeteiligung: Bool? = nil) {
        self.contractDate = contractDate
        self.einlage = einlage
        self.gewinnquotePct = gewinnquotePct
        self.gewinnvortrag = gewinnvortrag
        self.instrumentType = instrumentType
        self.kestPflichtig = kestPflichtig
        self.name = name
        self.notes = notes
        self.verlustVerrechnungskonto = verlustVerrechnungskonto
        self.verlustbeteiligung = verlustbeteiligung
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case contractDate
        case einlage
        case gewinnquotePct
        case gewinnvortrag
        case instrumentType
        case kestPflichtig
        case name
        case notes
        case verlustVerrechnungskonto
        case verlustbeteiligung
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(contractDate, forKey: .contractDate)
        try container.encodeIfPresent(einlage, forKey: .einlage)
        try container.encodeIfPresent(gewinnquotePct, forKey: .gewinnquotePct)
        try container.encodeIfPresent(gewinnvortrag, forKey: .gewinnvortrag)
        try container.encode(instrumentType, forKey: .instrumentType)
        try container.encodeIfPresent(kestPflichtig, forKey: .kestPflichtig)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(verlustVerrechnungskonto, forKey: .verlustVerrechnungskonto)
        try container.encodeIfPresent(verlustbeteiligung, forKey: .verlustbeteiligung)
    }
}

