//
// SupplierInvoiceCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SupplierInvoiceCreate: Codable, JSONEncodable, Hashable {

    public var currency: String?
    /** References the goods receipt entity. */
    public var goodsReceiptId: String?
    public var invoiceDate: Date
    public var invoiceNumber: String
    /** JSON array of `{product_id, name, quantity, unitPriceNet, taxRate}`. */
    public var lineItems: AnyCodable?
    public var notes: String?
    /** References the purchase order entity. */
    public var purchaseOrderId: String?
    /** One of: draft | matched | has_variances | posted | cancelled */
    public var status: SupplierInvoiceStatus
    /** References the supplier entity. */
    public var supplierContactId: String?
    public var supplierName: String?
    public var totalGrossAmount: String?
    public var totalNetAmount: String?

    public init(currency: String? = nil, goodsReceiptId: String? = nil, invoiceDate: Date, invoiceNumber: String, lineItems: AnyCodable?, notes: String? = nil, purchaseOrderId: String? = nil, status: SupplierInvoiceStatus, supplierContactId: String? = nil, supplierName: String? = nil, totalGrossAmount: String? = nil, totalNetAmount: String? = nil) {
        self.currency = currency
        self.goodsReceiptId = goodsReceiptId
        self.invoiceDate = invoiceDate
        self.invoiceNumber = invoiceNumber
        self.lineItems = lineItems
        self.notes = notes
        self.purchaseOrderId = purchaseOrderId
        self.status = status
        self.supplierContactId = supplierContactId
        self.supplierName = supplierName
        self.totalGrossAmount = totalGrossAmount
        self.totalNetAmount = totalNetAmount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currency
        case goodsReceiptId
        case invoiceDate
        case invoiceNumber
        case lineItems
        case notes
        case purchaseOrderId
        case status
        case supplierContactId
        case supplierName
        case totalGrossAmount
        case totalNetAmount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encodeIfPresent(goodsReceiptId, forKey: .goodsReceiptId)
        try container.encode(invoiceDate, forKey: .invoiceDate)
        try container.encode(invoiceNumber, forKey: .invoiceNumber)
        try container.encode(lineItems, forKey: .lineItems)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(purchaseOrderId, forKey: .purchaseOrderId)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(supplierContactId, forKey: .supplierContactId)
        try container.encodeIfPresent(supplierName, forKey: .supplierName)
        try container.encodeIfPresent(totalGrossAmount, forKey: .totalGrossAmount)
        try container.encodeIfPresent(totalNetAmount, forKey: .totalNetAmount)
    }
}

