//
// SupportChannelType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Support channel type: email or chat. */
public enum SupportChannelType: String, Codable, CaseIterable {
    case email = "email"
    case chat = "chat"
}
