//
// SupportTicketStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Support ticket status. */
public enum SupportTicketStatus: String, Codable, CaseIterable {
    case _open = "open"
    case awaitingReply = "awaiting_reply"
    case resolved = "resolved"
    case closed = "closed"
}
