//
// SyncLogStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Marketplace sync log status. */
public enum SyncLogStatus: String, Codable, CaseIterable {
    case running = "running"
    case success = "success"
    case error = "error"
}
