//
// SyncStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Marketplace sync status. */
public enum SyncStatus: String, Codable, CaseIterable {
    case pending = "pending"
    case connected = "connected"
    case success = "success"
    case error = "error"
}
