//
// SyncLog.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SyncLog: Codable, JSONEncodable, Hashable {

    public var completedAt: Date?
    public var connectionId: String
    public var errorMessage: String?
    public var itemsFailed: Int
    public var itemsSynced: Int
    public var logId: String
    public var platform: String
    public var startedAt: Date
    public var status: String
    public var syncType: String

    public init(completedAt: Date? = nil, connectionId: String, errorMessage: String? = nil, itemsFailed: Int, itemsSynced: Int, logId: String, platform: String, startedAt: Date, status: String, syncType: String) {
        self.completedAt = completedAt
        self.connectionId = connectionId
        self.errorMessage = errorMessage
        self.itemsFailed = itemsFailed
        self.itemsSynced = itemsSynced
        self.logId = logId
        self.platform = platform
        self.startedAt = startedAt
        self.status = status
        self.syncType = syncType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case completedAt = "completed_at"
        case connectionId = "connection_id"
        case errorMessage = "error_message"
        case itemsFailed = "items_failed"
        case itemsSynced = "items_synced"
        case logId = "log_id"
        case platform
        case startedAt = "started_at"
        case status
        case syncType = "sync_type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(completedAt, forKey: .completedAt)
        try container.encode(connectionId, forKey: .connectionId)
        try container.encodeIfPresent(errorMessage, forKey: .errorMessage)
        try container.encode(itemsFailed, forKey: .itemsFailed)
        try container.encode(itemsSynced, forKey: .itemsSynced)
        try container.encode(logId, forKey: .logId)
        try container.encode(platform, forKey: .platform)
        try container.encode(startedAt, forKey: .startedAt)
        try container.encode(status, forKey: .status)
        try container.encode(syncType, forKey: .syncType)
    }
}

