//
// TenantUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TenantUser: Codable, JSONEncodable, Hashable {

    public var email: String
    public var emailVerified: Bool
    public var isActive: Bool
    public var joinedAt: Date
    public var lastLogin: Date?
    public var name: String
    public var permissions: [String]
    public var role: String
    public var userId: UUID

    public init(email: String, emailVerified: Bool, isActive: Bool, joinedAt: Date, lastLogin: Date? = nil, name: String, permissions: [String], role: String, userId: UUID) {
        self.email = email
        self.emailVerified = emailVerified
        self.isActive = isActive
        self.joinedAt = joinedAt
        self.lastLogin = lastLogin
        self.name = name
        self.permissions = permissions
        self.role = role
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case emailVerified = "email_verified"
        case isActive = "is_active"
        case joinedAt = "joined_at"
        case lastLogin = "last_login"
        case name
        case permissions
        case role
        case userId = "user_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(emailVerified, forKey: .emailVerified)
        try container.encode(isActive, forKey: .isActive)
        try container.encode(joinedAt, forKey: .joinedAt)
        try container.encodeIfPresent(lastLogin, forKey: .lastLogin)
        try container.encode(name, forKey: .name)
        try container.encode(permissions, forKey: .permissions)
        try container.encode(role, forKey: .role)
        try container.encode(userId, forKey: .userId)
    }
}

