//
// UmsatzsteuerReport.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UmsatzsteuerReport: Codable, JSONEncodable, Hashable {

    public var generatedAt: String
    public var inputTax: [VatDetail]
    public var outputTax: [VatDetail]
    public var period: String
    public var totalInputTax: String
    public var totalOutputTax: String
    public var vatPayable: String
    public var vatRefund: String

    public init(generatedAt: String, inputTax: [VatDetail], outputTax: [VatDetail], period: String, totalInputTax: String, totalOutputTax: String, vatPayable: String, vatRefund: String) {
        self.generatedAt = generatedAt
        self.inputTax = inputTax
        self.outputTax = outputTax
        self.period = period
        self.totalInputTax = totalInputTax
        self.totalOutputTax = totalOutputTax
        self.vatPayable = vatPayable
        self.vatRefund = vatRefund
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case generatedAt = "generated_at"
        case inputTax = "input_tax"
        case outputTax = "output_tax"
        case period
        case totalInputTax = "total_input_tax"
        case totalOutputTax = "total_output_tax"
        case vatPayable = "vat_payable"
        case vatRefund = "vat_refund"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(generatedAt, forKey: .generatedAt)
        try container.encode(inputTax, forKey: .inputTax)
        try container.encode(outputTax, forKey: .outputTax)
        try container.encode(period, forKey: .period)
        try container.encode(totalInputTax, forKey: .totalInputTax)
        try container.encode(totalOutputTax, forKey: .totalOutputTax)
        try container.encode(vatPayable, forKey: .vatPayable)
        try container.encode(vatRefund, forKey: .vatRefund)
    }
}

