//
// UpdateAutomation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateAutomation: Codable, JSONEncodable, Hashable {

    public var config: AnyCodable?
    public var enabled: Bool?

    public init(config: AnyCodable? = nil, enabled: Bool? = nil) {
        self.config = config
        self.enabled = enabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case config
        case enabled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(config, forKey: .config)
        try container.encodeIfPresent(enabled, forKey: .enabled)
    }
}

