//
// UpsCredentials.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpsCredentials: Codable, JSONEncodable, Hashable {

    /** OAuth 2.0 client credentials from developer.ups.com. */
    public var clientId: String
    public var clientSecret: String
    /** UPS account number; required for label creation, optional for rates/tracking. */
    public var shipperNumber: String?

    public init(clientId: String, clientSecret: String, shipperNumber: String? = nil) {
        self.clientId = clientId
        self.clientSecret = clientSecret
        self.shipperNumber = shipperNumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clientId = "client_id"
        case clientSecret = "client_secret"
        case shipperNumber = "shipper_number"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(clientId, forKey: .clientId)
        try container.encode(clientSecret, forKey: .clientSecret)
        try container.encodeIfPresent(shipperNumber, forKey: .shipperNumber)
    }
}

