//
// UstvaErgebnis.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UstvaErgebnis: Codable, JSONEncodable, Hashable {

    public var bis: String
    public var hinweis: String?
    public var istKleinunternehmer: Bool
    public var kz41: String
    public var kz43: String
    public var kz46: String
    public var kz47: String
    public var kz61: String
    public var kz66: String
    public var kz67: String
    public var kz81: String
    public var kz83: String
    public var kz84: String
    public var kz85: String
    public var kz86: String
    public var kz88: String
    public var kz89: String
    public var kz93: String
    public var von: String
    public var zahllast: String
    public var zeitraum: String
    public var zeitraumTyp: String

    public init(bis: String, hinweis: String? = nil, istKleinunternehmer: Bool, kz41: String, kz43: String, kz46: String, kz47: String, kz61: String, kz66: String, kz67: String, kz81: String, kz83: String, kz84: String, kz85: String, kz86: String, kz88: String, kz89: String, kz93: String, von: String, zahllast: String, zeitraum: String, zeitraumTyp: String) {
        self.bis = bis
        self.hinweis = hinweis
        self.istKleinunternehmer = istKleinunternehmer
        self.kz41 = kz41
        self.kz43 = kz43
        self.kz46 = kz46
        self.kz47 = kz47
        self.kz61 = kz61
        self.kz66 = kz66
        self.kz67 = kz67
        self.kz81 = kz81
        self.kz83 = kz83
        self.kz84 = kz84
        self.kz85 = kz85
        self.kz86 = kz86
        self.kz88 = kz88
        self.kz89 = kz89
        self.kz93 = kz93
        self.von = von
        self.zahllast = zahllast
        self.zeitraum = zeitraum
        self.zeitraumTyp = zeitraumTyp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bis
        case hinweis
        case istKleinunternehmer = "ist_kleinunternehmer"
        case kz41 = "kz_41"
        case kz43 = "kz_43"
        case kz46 = "kz_46"
        case kz47 = "kz_47"
        case kz61 = "kz_61"
        case kz66 = "kz_66"
        case kz67 = "kz_67"
        case kz81 = "kz_81"
        case kz83 = "kz_83"
        case kz84 = "kz_84"
        case kz85 = "kz_85"
        case kz86 = "kz_86"
        case kz88 = "kz_88"
        case kz89 = "kz_89"
        case kz93 = "kz_93"
        case von
        case zahllast
        case zeitraum
        case zeitraumTyp = "zeitraum_typ"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(bis, forKey: .bis)
        try container.encodeIfPresent(hinweis, forKey: .hinweis)
        try container.encode(istKleinunternehmer, forKey: .istKleinunternehmer)
        try container.encode(kz41, forKey: .kz41)
        try container.encode(kz43, forKey: .kz43)
        try container.encode(kz46, forKey: .kz46)
        try container.encode(kz47, forKey: .kz47)
        try container.encode(kz61, forKey: .kz61)
        try container.encode(kz66, forKey: .kz66)
        try container.encode(kz67, forKey: .kz67)
        try container.encode(kz81, forKey: .kz81)
        try container.encode(kz83, forKey: .kz83)
        try container.encode(kz84, forKey: .kz84)
        try container.encode(kz85, forKey: .kz85)
        try container.encode(kz86, forKey: .kz86)
        try container.encode(kz88, forKey: .kz88)
        try container.encode(kz89, forKey: .kz89)
        try container.encode(kz93, forKey: .kz93)
        try container.encode(von, forKey: .von)
        try container.encode(zahllast, forKey: .zahllast)
        try container.encode(zeitraum, forKey: .zeitraum)
        try container.encode(zeitraumTyp, forKey: .zeitraumTyp)
    }
}

