//
// VatItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VatItem: Codable, JSONEncodable, Hashable {

    public var netAmount: String
    public var taxAmount: String
    public var taxRate: String

    public init(netAmount: String, taxAmount: String, taxRate: String) {
        self.netAmount = netAmount
        self.taxAmount = taxAmount
        self.taxRate = taxRate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case netAmount = "net_amount"
        case taxAmount = "tax_amount"
        case taxRate = "tax_rate"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(netAmount, forKey: .netAmount)
        try container.encode(taxAmount, forKey: .taxAmount)
        try container.encode(taxRate, forKey: .taxRate)
    }
}

