//
// VatSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VatSummary: Codable, JSONEncodable, Hashable {

    public var inputTaxItems: [VatItem]
    public var outputTaxItems: [VatItem]
    public var totalInputTax: String
    public var totalOutputTax: String
    public var vatDue: String

    public init(inputTaxItems: [VatItem], outputTaxItems: [VatItem], totalInputTax: String, totalOutputTax: String, vatDue: String) {
        self.inputTaxItems = inputTaxItems
        self.outputTaxItems = outputTaxItems
        self.totalInputTax = totalInputTax
        self.totalOutputTax = totalOutputTax
        self.vatDue = vatDue
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case inputTaxItems = "input_tax_items"
        case outputTaxItems = "output_tax_items"
        case totalInputTax = "total_input_tax"
        case totalOutputTax = "total_output_tax"
        case vatDue = "vat_due"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(inputTaxItems, forKey: .inputTaxItems)
        try container.encode(outputTaxItems, forKey: .outputTaxItems)
        try container.encode(totalInputTax, forKey: .totalInputTax)
        try container.encode(totalOutputTax, forKey: .totalOutputTax)
        try container.encode(vatDue, forKey: .vatDue)
    }
}

