//
// VoucherCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VoucherCreate: Codable, JSONEncodable, Hashable {

    public var categoryId: String?
    /** References the contact entity. */
    public var contactId: String?
    public var contactName: String?
    public var currency: String
    public var description: String?
    public var fileAttachments: AnyCodable?
    public var lineItems: AnyCodable?
    public var metadata: AnyCodable?
    public var notes: String?
    public var openAmount: String?
    public var paidDate: Date?
    public var paymentStatus: PaymentStatus?
    public var taxAmounts: AnyCodable?
    public var taxCondition: String?
    public var totalGrossAmount: String?
    public var totalNetAmount: String?
    public var voucherDate: Date
    public var voucherNumber: String?
    public var voucherStatus: VoucherStatus
    public var voucherType: VoucherType

    public init(categoryId: String? = nil, contactId: String? = nil, contactName: String? = nil, currency: String, description: String? = nil, fileAttachments: AnyCodable? = nil, lineItems: AnyCodable? = nil, metadata: AnyCodable? = nil, notes: String? = nil, openAmount: String? = nil, paidDate: Date? = nil, paymentStatus: PaymentStatus? = nil, taxAmounts: AnyCodable? = nil, taxCondition: String? = nil, totalGrossAmount: String? = nil, totalNetAmount: String? = nil, voucherDate: Date, voucherNumber: String? = nil, voucherStatus: VoucherStatus, voucherType: VoucherType) {
        self.categoryId = categoryId
        self.contactId = contactId
        self.contactName = contactName
        self.currency = currency
        self.description = description
        self.fileAttachments = fileAttachments
        self.lineItems = lineItems
        self.metadata = metadata
        self.notes = notes
        self.openAmount = openAmount
        self.paidDate = paidDate
        self.paymentStatus = paymentStatus
        self.taxAmounts = taxAmounts
        self.taxCondition = taxCondition
        self.totalGrossAmount = totalGrossAmount
        self.totalNetAmount = totalNetAmount
        self.voucherDate = voucherDate
        self.voucherNumber = voucherNumber
        self.voucherStatus = voucherStatus
        self.voucherType = voucherType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case categoryId
        case contactId
        case contactName
        case currency
        case description
        case fileAttachments
        case lineItems
        case metadata
        case notes
        case openAmount
        case paidDate
        case paymentStatus
        case taxAmounts
        case taxCondition
        case totalGrossAmount
        case totalNetAmount
        case voucherDate
        case voucherNumber
        case voucherStatus
        case voucherType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(categoryId, forKey: .categoryId)
        try container.encodeIfPresent(contactId, forKey: .contactId)
        try container.encodeIfPresent(contactName, forKey: .contactName)
        try container.encode(currency, forKey: .currency)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(fileAttachments, forKey: .fileAttachments)
        try container.encodeIfPresent(lineItems, forKey: .lineItems)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(openAmount, forKey: .openAmount)
        try container.encodeIfPresent(paidDate, forKey: .paidDate)
        try container.encodeIfPresent(paymentStatus, forKey: .paymentStatus)
        try container.encodeIfPresent(taxAmounts, forKey: .taxAmounts)
        try container.encodeIfPresent(taxCondition, forKey: .taxCondition)
        try container.encodeIfPresent(totalGrossAmount, forKey: .totalGrossAmount)
        try container.encodeIfPresent(totalNetAmount, forKey: .totalNetAmount)
        try container.encode(voucherDate, forKey: .voucherDate)
        try container.encodeIfPresent(voucherNumber, forKey: .voucherNumber)
        try container.encode(voucherStatus, forKey: .voucherStatus)
        try container.encode(voucherType, forKey: .voucherType)
    }
}

