//
// YearlyPayrollSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct YearlyPayrollSummary: Codable, JSONEncodable, Hashable {

    public var avgEmployeeCount: Int
    public var months: [PayrollSummaryItem]
    public var year: Int
    public var yearlyEmployerCost: String
    public var yearlyGross: String
    public var yearlyNet: String

    public init(avgEmployeeCount: Int, months: [PayrollSummaryItem], year: Int, yearlyEmployerCost: String, yearlyGross: String, yearlyNet: String) {
        self.avgEmployeeCount = avgEmployeeCount
        self.months = months
        self.year = year
        self.yearlyEmployerCost = yearlyEmployerCost
        self.yearlyGross = yearlyGross
        self.yearlyNet = yearlyNet
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case avgEmployeeCount = "avg_employee_count"
        case months
        case year
        case yearlyEmployerCost = "yearly_employer_cost"
        case yearlyGross = "yearly_gross"
        case yearlyNet = "yearly_net"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(avgEmployeeCount, forKey: .avgEmployeeCount)
        try container.encode(months, forKey: .months)
        try container.encode(year, forKey: .year)
        try container.encode(yearlyEmployerCost, forKey: .yearlyEmployerCost)
        try container.encode(yearlyGross, forKey: .yearlyGross)
        try container.encode(yearlyNet, forKey: .yearlyNet)
    }
}

